export const FAMILY_TEMPLATES: Record<string, { id: number; image: string; description: string }> = {
  software_engineering:          { id: 1,  image: '/assets/templates/software_engineering.png', description: 'Modern template for tech professionals' },
  healthcare:                    { id: 2,  image: '/assets/templates/healthcare.png',            description: 'Professional template for healthcare' },
  finance:                       { id: 3,  image: '/assets/templates/finance.png',               description: 'Professional layout for finance professionals' },
  education:                     { id: 4,  image: '/assets/templates/education.png',             description: 'Template for educators and academics' },
  cybersecurity:                 { id: 5,  image: '/assets/templates/cybersecurity.png',         description: 'Specialized template for security professionals' },
  core_engineering:              { id: 6,  image: '/assets/templates/core-engineering.png',      description: 'Template for mechanical, civil, and core engineers' },
  electronics_and_vlsi:          { id: 7,  image: '/assets/templates/electronics_vlsi.png',      description: 'Technical template for electronics professionals' },
  government_standard:           { id: 8,  image: '/assets/templates/government_standard.png',   description: 'Official format for government job applications' },
  legal:                         { id: 9,  image: '/assets/templates/legal.png',                 description: 'Professional template for legal professionals' },
  logistics_warehouse_operations:{ id: 10, image: '/assets/templates/logistics.png',             description: 'Template for logistics and warehouse operations' },
  marine_merchant_navy:          { id: 11, image: '/assets/templates/marine_merchant.png',       description: 'Professional template for maritime professionals' },
  modern_minimal_template:       { id: 12, image: '/assets/templates/modern_minimal.png',        description: 'Clean and minimal design for any profession' },
  research_scholar:              { id: 13, image: '/assets/templates/research_scholar.png',      description: 'Academic template for researchers and scholars' },
  sales_business_development:    { id: 14, image: '/assets/templates/sales_business.png',        description: 'Dynamic template for sales professionals' },
  general_professional:          { id: 1,  image: '/assets/templates/software_engineering.png',  description: 'Professional template for any industry' },
}

export const FAMILY_DOMAINS: Record<string, string[]> = {
  software_engineering:           ['software_engineering', 'web_development', 'full_stack_development', 'mobile_development', 'devops', 'cloud_engineering', 'data_science', 'machine_learning', 'ux_ui_design'],
  core_engineering:               ['mechanical_engineering', 'civil_engineering', 'chemical_engineering', 'aerospace_engineering', 'automotive_engineering', 'construction_engineering', 'robotics', 'plc_scada'],
  healthcare:                     ['doctor_physician', 'surgeon', 'clinical_nurse', 'pharmacist', 'physiotherapist', 'radiologist', 'medical_lab_scientist', 'healthcare_administrator'],
  finance:                        ['accounting', 'financial_planning', 'financial_analysis', 'investment_banking', 'corporate_finance', 'banking', 'audit', 'risk_management', 'mba_general_management'],
  education:                      ['professor', 'associate_professor', 'assistant_professor', 'senior_lecturer', 'lecturer', 'teacher', 'academic_researcher', 'education_director', 'department_head'],
  cybersecurity:                  ['cybersecurity', 'application_security', 'penetration_testers', 'soc_analysts', 'incident_response', 'digital_forensics', 'security_engineers', 'grc', 'compliance_officers'],
  electronics_and_vlsi:           ['embedded_systems', 'vlsi_design', 'semiconductor', 'iot', 'automation'],
  government_standard:            ['civil_services', 'defense', 'drdo', 'isro', 'psu', 'ias', 'railways', 'ciso'],
  legal:                          ['ip_attorneys', 'law_firms', 'legal_operations', 'paralegals'],
  logistics_warehouse_operations: ['operations', 'procurement', 'scm', 'warehousing', 'distribution', 'freight', 'shipping', 'port_operations', 'demand_planning'],
  marine_merchant_navy:           ['merchant_navy', 'marine_engineering', 'naval_architecture', 'offshore'],
  modern_minimal_template:        ['hr', 'marketing', 'product_management', 'management_consulting', 'design', 'insurance', 'hospitality_management'],
  research_scholar:               ['academic_researcher', 'biotech', 'pharma', 'life_sciences', 'regulatory_affairs'],
  sales_business_development:     ['sales', 'business_development', 'account_management', 'growth', 'marketing', 'startups'],
  general_professional:           ['general_professional', 'hr', 'operations', 'management_consulting'],
}

export const DOMAIN_NAMES: Record<string, string> = {
  software_engineering: 'Software Engineering',
  core_engineering: 'Core Engineering',
  healthcare: 'Healthcare',
  finance: 'Finance',
  education: 'Education',
  cybersecurity: 'Cybersecurity',
  electronics_and_vlsi: 'Electronics & VLSI',
  government_standard: 'Government Standard',
  legal: 'Legal',
  logistics_warehouse_operations: 'Logistics & Warehouse Operations',
  marine_merchant_navy: 'Marine & Merchant Navy',
  modern_minimal_template: 'Modern Minimal',
  research_scholar: 'Research Scholar',
  sales_business_development: 'Sales & Business Development',
  general_professional: 'General Professional',
}

export const DOMAIN_DISPLAY_NAMES: Record<string, string> = {
  aerospace_engineering: 'Aerospace Engineer',
  automotive_engineering: 'Automotive Engineer',
  chemical_engineering: 'Chemical Engineer',
  civil_engineering: 'Civil Engineer',
  construction_engineering: 'Construction Engineer',
  devops: 'DevOps Engineer',
  embedded_systems: 'Embedded Systems Engineer',
  marine_engineering: 'Marine Engineer',
  mechanical_engineering: 'Mechanical Engineer',
  naval_architecture: 'Naval Architect',
  semiconductor: 'Semiconductor Engineer',
  vlsi_design: 'VLSI Design Engineer',
  robotics: 'Robotics Engineer',
  plc_scada: 'PLC/SCADA Engineer',
  professor: 'Professor',
  associate_professor: 'Associate Professor',
  assistant_professor: 'Assistant Professor',
  senior_lecturer: 'Senior Lecturer',
  lecturer: 'Lecturer',
  senior_teacher: 'Senior Teacher',
  principal_teacher: 'Principal Teacher',
  teacher: 'Teacher',
  visiting_faculty: 'Visiting Faculty',
  academic_dean: 'Academic Dean',
  academic_researcher: 'Academic Researcher',
  education_director: 'Education Director',
  education_coordinator: 'Education Coordinator',
  department_head: 'Department Head',
  doctor_physician: 'Doctor / Physician',
  surgeon: 'Surgeon',
  clinical_nurse: 'Clinical Nurse',
  pharmacist: 'Pharmacist',
  physiotherapist: 'Physiotherapist',
  radiologist: 'Radiologist',
  medical_lab_scientist: 'Medical Lab Scientist',
  healthcare_administrator: 'Healthcare Administrator',
  software_engineering: 'Software Engineer',
  data_science: 'Data Scientist',
  cloud_computing: 'Cloud Computing Specialist',
  cloud_engineering: 'Cloud Engineer',
  cybersecurity: 'Cybersecurity Specialist',
  application_security: 'Application Security Engineer',
  security_engineers: 'Security Engineer',
  incident_response: 'Incident Response Specialist',
  penetration_testers: 'Penetration Tester',
  soc_analysts: 'SOC Analyst',
  digital_forensics: 'Digital Forensics Specialist',
  ux_ui_design: 'UX / UI Designer',
  web_development: 'Web Developer',
  full_stack_development: 'Full Stack Developer',
  mobile_development: 'Mobile Developer',
  machine_learning: 'Machine Learning Engineer',
  accounting: 'Accountant',
  financial_planning: 'Financial Planner',
  financial_analysis: 'Financial Analyst',
  investment_banking: 'Investment Banker',
  corporate_finance: 'Corporate Finance Professional',
  banking: 'Banking Professional',
  audit: 'Audit Professional',
  risk_management: 'Risk Manager',
  mba_general_management: 'MBA / General Management',
  ip_attorneys: 'IP Attorney',
  law_firms: 'Lawyer / Law Firm Professional',
  legal_operations: 'Legal Operations Specialist',
  paralegals: 'Paralegal',
  hr: 'HR Professional',
  account_management: 'Account Manager',
  sales: 'Sales Professional',
  marketing: 'Marketing Professional',
  business_development: 'Business Development Executive',
  product_management: 'Product Manager',
  growth: 'Growth Specialist',
  startups: 'Startup Professional',
  operations: 'Operations Manager',
  procurement: 'Procurement Specialist',
  scm: 'Supply Chain Manager',
  demand_planning: 'Demand Planner',
  inventory_management: 'Inventory Manager',
  distribution: 'Distribution Manager',
  freight: 'Freight Specialist',
  shipping: 'Shipping Specialist',
  warehousing: 'Warehouse Manager',
  port_operations: 'Port Operations Specialist',
  civil_services: 'Civil Services Officer',
  defense: 'Defense Professional',
  drdo: 'DRDO Scientist',
  isro: 'ISRO Scientist',
  psu: 'PSU Professional',
  ias: 'IAS Officer',
  railways: 'Railways Professional',
  ciso: 'CISO',
  compliance_officers: 'Compliance Officer',
  grc: 'GRC Specialist',
  merchant_navy: 'Merchant Navy Officer',
  offshore: 'Offshore Professional',
  biotech: 'Biotech Professional',
  pharma: 'Pharmaceutical Professional',
  hospitality_management: 'Hospitality Manager',
  insurance: 'Insurance Professional',
  regulatory_affairs: 'Regulatory Affairs Specialist',
  management_consulting: 'Management Consultant',
  design: 'Designer',
  automation: 'Automation Specialist',
  iot: 'IoT Engineer',
  life_sciences: 'Life Sciences Professional',
  general_professional: 'General Professional',
}

export const CAREER_LEVELS = ['Fresher', 'Early Career', 'Mid-Level', 'Senior-Level', 'Manager']

export const FALLBACK_IMAGE = '/assets/templates/template-1.png'
