export const locations: string[] = [
  // United States - Major Cities
  "New York, NY",
  "San Francisco, CA",
  "Los Angeles, CA",
  "Chicago, IL",
  "Boston, MA",
  "Seattle, WA",
  "Austin, TX",
  "Washington, DC",
  "Denver, CO",
  "Atlanta, GA",
  "Miami, FL",
  "Philadelphia, PA",
  "Phoenix, AZ",
  "San Diego, CA",
  "Dallas, TX",
  "Houston, TX",
  "Portland, OR",
  "Minneapolis, MN",
  "Detroit, MI",
  "Nashville, TN",
  "Charlotte, NC",
  "Raleigh, NC",
  "Salt Lake City, UT",
  "Las Vegas, NV",
  "San Jose, CA",
  "Columbus, OH",
  "Indianapolis, IN",
  "Jacksonville, FL",
  "San Antonio, TX",
  "Fort Worth, TX",
  "Milwaukee, WI",
  "Oklahoma City, OK",
  "Albuquerque, NM",
  "Tucson, AZ",
  "Sacramento, CA",
  "Kansas City, MO",
  "Cleveland, OH",
  "Virginia Beach, VA",
  "Omaha, NE",
  "Oakland, CA",
  "Raleigh, NC",
  "Long Beach, CA",
  "Colorado Springs, CO",
  "Tampa, FL",
  "Pittsburgh, PA",
  "St. Louis, MO",
  "Cincinnati, OH",
  "Newark, NJ",
  "Jersey City, NJ",
  "Buffalo, NY",
  
  // India - Major Cities
  "Mumbai, India",
  "Bangalore, India",
  "Delhi, India",
  "Hyderabad, India",
  "Pune, India",
  "Chennai, India",
  "Kolkata, India",
  "Ahmedabad, India",
  "Gurugram, India",
  "Noida, India",
  "Gurgaon, India",
  "Jaipur, India",
  "Surat, India",
  "Lucknow, India",
  "Kanpur, India",
  "Nagpur, India",
  "Indore, India",
  "Thane, India",
  "Bhopal, India",
  "Visakhapatnam, India",
  "Vadodara, India",
  "Coimbatore, India",
  "Kochi, India",
  "Chandigarh, India",
  "Mysore, India",
  
  // United Kingdom
  "London, UK",
  "Manchester, UK",
  "Birmingham, UK",
  "Edinburgh, UK",
  "Glasgow, UK",
  "Liverpool, UK",
  "Bristol, UK",
  "Leeds, UK",
  "Sheffield, UK",
  "Newcastle, UK",
  "Cardiff, UK",
  "Belfast, UK",
  "Nottingham, UK",
  "Southampton, UK",
  "Cambridge, UK",
  "Oxford, UK",
  
  // Canada
  "Toronto, Canada",
  "Vancouver, Canada",
  "Montreal, Canada",
  "Calgary, Canada",
  "Ottawa, Canada",
  "Edmonton, Canada",
  "Mississauga, Canada",
  "Winnipeg, Canada",
  "Quebec City, Canada",
  "Hamilton, Canada",
  
  // Australia
  "Sydney, Australia",
  "Melbourne, Australia",
  "Brisbane, Australia",
  "Perth, Australia",
  "Adelaide, Australia",
  "Canberra, Australia",
  
  // Europe
  "Berlin, Germany",
  "Munich, Germany",
  "Frankfurt, Germany",
  "Hamburg, Germany",
  "Cologne, Germany",
  "Paris, France",
  "Lyon, France",
  "Marseille, France",
  "Toulouse, France",
  "Amsterdam, Netherlands",
  "Rotterdam, Netherlands",
  "The Hague, Netherlands",
  "Stockholm, Sweden",
  "Gothenburg, Sweden",
  "Copenhagen, Denmark",
  "Oslo, Norway",
  "Helsinki, Finland",
  "Zurich, Switzerland",
  "Geneva, Switzerland",
  "Brussels, Belgium",
  "Vienna, Austria",
  "Dublin, Ireland",
  "Madrid, Spain",
  "Barcelona, Spain",
  "Milan, Italy",
  "Rome, Italy",
  "Prague, Czech Republic",
  "Warsaw, Poland",
  "Krakow, Poland",
  "Lisbon, Portugal",
  "Athens, Greece",
  
  // Asia Pacific
  "Singapore",
  "Hong Kong",
  "Tokyo, Japan",
  "Osaka, Japan",
  "Seoul, South Korea",
  "Beijing, China",
  "Shanghai, China",
  "Shenzhen, China",
  "Guangzhou, China",
  "Bangkok, Thailand",
  "Kuala Lumpur, Malaysia",
  "Manila, Philippines",
  "Jakarta, Indonesia",
  "Ho Chi Minh City, Vietnam",
  "Hanoi, Vietnam",
  "Taipei, Taiwan",
  
  // Middle East
  "Dubai, UAE",
  "Abu Dhabi, UAE",
  "Riyadh, Saudi Arabia",
  "Doha, Qatar",
  "Kuwait City, Kuwait",
  "Tel Aviv, Israel",
  "Beirut, Lebanon",
  "Amman, Jordan",
  "Muscat, Oman",
  "Manama, Bahrain",
  
  // Africa
  "Cape Town, South Africa",
  "Johannesburg, South Africa",
  "Lagos, Nigeria",
  "Nairobi, Kenya",
  "Cairo, Egypt",
  "Casablanca, Morocco",
  "Accra, Ghana",
  
  // Latin America
  "Mexico City, Mexico",
  "Guadalajara, Mexico",
  "Monterrey, Mexico",
  "São Paulo, Brazil",
  "Rio de Janeiro, Brazil",
  "Buenos Aires, Argentina",
  "Bogotá, Colombia",
  "Lima, Peru",
  "Santiago, Chile",
  
  // Work Arrangements
  "Remote",
  "Hybrid",
  "Remote - US",
  "Remote - Global",
  "Remote - Europe",
  "Remote - Asia",
];
