export const roles: string[] = [
  // Software Engineering
  "Developer",
  "Software Engineer",
  "Senior Software Engineer",
  "Staff Software Engineer",
  "Principal Software Engineer",
  "Lead Software Engineer",
  "Software Developer",
  "Full Stack Developer",
  "Frontend Developer",
  "Backend Developer",
  "Full-Stack Engineer",
  "Frontend Engineer",
  "Backend Engineer",
  "Web Developer",
  "Mobile Developer",
  "iOS Developer",
  "Android Developer",
  "React Developer",
  "React Native Developer",
  "Node.js Developer",
  "Python Developer",
  "Java Developer",
  ".NET Developer",
  "PHP Developer",
  "Ruby Developer",
  "Go Developer",
  "Rust Developer",
  
  // DevOps & Infrastructure
  "DevOps Engineer",
  "Site Reliability Engineer",
  "Platform Engineer",
  "Cloud Engineer",
  "Infrastructure Engineer",
  "Systems Engineer",
  "Network Engineer",
  "Security Engineer",
  "Cybersecurity Engineer",
  "Cloud Architect",
  "Solutions Architect",
  "Systems Administrator",
  "Database Administrator",
  
  // Data & Analytics
  "Data Scientist",
  "Senior Data Scientist",
  "Machine Learning Engineer",
  "Data Engineer",
  "Data Analyst",
  "Business Intelligence Analyst",
  "Analytics Engineer",
  "AI Engineer",
  "Research Scientist",
  "Applied Scientist",
  "Deep Learning Engineer",
  "NLP Engineer",
  "Computer Vision Engineer",
  "MLOps Engineer",
  
  // Engineering Leadership
  "Engineering Manager",
  "Senior Engineering Manager",
  "Director of Engineering",
  "VP of Engineering",
  "Chief Technology Officer",
  "CTO",
  "Technical Lead",
  "Tech Lead",
  "Team Lead",
  "Engineering Lead",
  
  // Product & Design
  "Product Manager",
  "Senior Product Manager",
  "Product Owner",
  "Technical Product Manager",
  "Product Designer",
  "UX Designer",
  "UI Designer",
  "UX/UI Designer",
  "Product Design Lead",
  "Design Lead",
  "Creative Director",
  "UX Researcher",
  "Product Analyst",
  
  // Quality Assurance
  "QA Engineer",
  "Quality Assurance Engineer",
  "Test Engineer",
  "Automation Engineer",
  "SDET",
  "Software Development Engineer in Test",
  "QA Lead",
  "Test Automation Engineer",
  
  // Specialized Technical
  "Blockchain Developer",
  "Smart Contract Developer",
  "Game Developer",
  "Unity Developer",
  "Unreal Engine Developer",
  "Embedded Systems Engineer",
  "Firmware Engineer",
  "Hardware Engineer",
  "IoT Engineer",
  "Robotics Engineer",
  "AR/VR Developer",
  "Graphics Engineer",
  
  // Business & Strategy
  "Business Analyst",
  "Strategy Consultant",
  "Management Consultant",
  "Operations Manager",
  "Project Manager",
  "Program Manager",
  "Technical Program Manager",
  "Scrum Master",
  "Agile Coach",
  "Product Operations Manager",
  
  // Sales & Marketing
  "Sales Engineer",
  "Solutions Engineer",
  "Customer Success Manager",
  "Account Executive",
  "Business Development Manager",
  "Marketing Manager",
  "Digital Marketing Manager",
  "Growth Manager",
  "Content Marketing Manager",
  "SEO Specialist",
  "Performance Marketing Manager",
  
  // Finance & Accounting
  "Financial Analyst",
  "Senior Financial Analyst",
  "Accountant",
  "Senior Accountant",
  "Financial Controller",
  "Finance Manager",
  "Investment Analyst",
  "Risk Analyst",
  "Auditor",
  "Tax Analyst",
  
  // Human Resources
  "HR Manager",
  "Human Resources Manager",
  "Recruiter",
  "Technical Recruiter",
  "Talent Acquisition Manager",
  "People Operations Manager",
  "HR Business Partner",
  "Compensation Analyst",
  "Learning & Development Manager",
  
  // Operations
  "Operations Analyst",
  "Supply Chain Manager",
  "Logistics Manager",
  "Procurement Manager",
  "Facilities Manager",
  "Office Manager",
  "Operations Coordinator",
  
  // Legal & Compliance
  "Legal Counsel",
  "Compliance Officer",
  "Compliance Analyst",
  "Paralegal",
  "Contract Manager",
  "Intellectual Property Attorney",
  
  // Customer Support
  "Customer Support Engineer",
  "Technical Support Engineer",
  "Support Engineer",
  "Customer Support Specialist",
  "Technical Support Specialist",
  "Customer Success Engineer",
  
  // Research & Development
  "Research Engineer",
  "R&D Engineer",
  "Research Analyst",
  "Research Associate",
  "Lab Technician",
  "Research Scientist",
  
  // Internships & Entry Level
  "Developer Intern",
  "Software Engineering Intern",
  "Data Science Intern",
  "Product Management Intern",
  "Marketing Intern",
  "Business Analyst Intern",
  "Junior Software Engineer",
  "Junior Developer",
  "Associate Software Engineer",
  "Graduate Engineer",
  "Trainee Engineer",
  
  // Executive & C-Level
  "Chief Executive Officer",
  "CEO",
  "Chief Operating Officer",
  "COO",
  "Chief Financial Officer",
  "CFO",
  "Chief Marketing Officer",
  "CMO",
  "Chief Product Officer",
  "CPO",
  "Chief Data Officer",
  "CDO",
  "Chief Information Officer",
  "CIO",
  "Chief Security Officer",
  "CSO",
  "VP of Product",
  "VP of Sales",
  "VP of Marketing",
  "VP of Operations",
  "General Manager",
  "Managing Director",
];
