'use client';

import { useState, useEffect, useCallback, useRef } from 'react';
import { useRouter, useParams, useSearchParams } from 'next/navigation';
import { ChevronLeft, ChevronRight, Flag, EyeOff, AlertTriangle, CheckCircle } from 'lucide-react';
import { motion, AnimatePresence } from 'framer-motion';
import { toast } from 'sonner';
import { resolveCompanyId, resolveCompanyInfo, CATEGORY_SUBCATEGORIES } from '@/lib/mockTestConstants';
import {
  generateMockTest,
  getSectionQuestions,
  submitAnswer,
  submitTest,
  submitParentSession,
  reportIssue,
  getActiveSession,
  MockTestSection,
  MockTestSession,
  AnswerFeedback,
} from '@/api/mockTestApi';

// ─── Types ───────────────────────────────────────────────────────────────────

interface Question {
  id: number | string;
  section: string;
  text: string;
  options: string[];
  selected: string | null;
  markedForReview: boolean;
}

type Phase = 'loading' | 'section_intro' | 'section_testing' | 'results_summary' | 'submitting';

interface SectionResult {
  name: string;
  answered: number;
  total: number;
}

// ─── Static maps ─────────────────────────────────────────────────────────────


const negMarkingSections: Record<string, string[]> = {
  '1': ['Quantitative Aptitude', 'Reasoning Ability', 'Programming Logic'],
};



// ─── Helpers ─────────────────────────────────────────────────────────────────

function getSectionTags(sectionName: string): string[] {
  const n = (sectionName || '').toLowerCase();
  if (n.includes('arithmetic')) return ['Percentages', 'Time & Work', 'Profit & Loss', 'Ratios', 'Number Systems'];
  if (n.includes('aptitude'))   return ['Data Interpretation', 'Averages', 'Permutations', 'Probability'];
  if (n.includes('reasoning'))  return ['Logical Sequences', 'Blood Relations', 'Directions', 'Coding-Decoding'];
  if (n.includes('technical'))  return ['CS Fundamentals', 'Algorithms', 'OOP', 'DSA'];
  return [sectionName];
}

// ─── Component ───────────────────────────────────────────────────────────────

export default function MockTestPage() {
  const router = useRouter();
  const params = useParams();
  const searchParams = useSearchParams();
  const urlTestId = params.id as string;
  const initialSessionId = searchParams.get('sessionId');
  // Parent session ID pre-generated by custom builder so all sections share one parent
  const initialParentSessionId = searchParams.get('parentSessionId');

  const isCustomTest = urlTestId === 'custom-test';
  const testId = resolveCompanyId(urlTestId);

  // Custom test config from query params
  const customCategories = isCustomTest
    ? (searchParams.get('categories') ?? 'arithmetic').split(',').filter(Boolean)
    : null;

  // Section progression: Arithmetic(0) → Aptitude(1) → Reasoning(2) → Technical(3)

  const STATIC_SECTION_PROGRESSION = [
    { name: 'arithmetic', subcategories: CATEGORY_SUBCATEGORIES['arithmetic'] },
    { name: 'aptitude',   subcategories: CATEGORY_SUBCATEGORIES['aptitude'] },
    { name: 'reasoning',  subcategories: CATEGORY_SUBCATEGORIES['reasoning'] },
    { name: 'technical',  subcategories: CATEGORY_SUBCATEGORIES['technical'] },
  ];

  const SECTION_PROGRESSION = isCustomTest && customCategories && customCategories.length > 0
    ? customCategories.map(cat => ({
        name: cat,
        subcategories: CATEGORY_SUBCATEGORIES[cat] ?? [cat],
      }))
    : STATIC_SECTION_PROGRESSION;

  // Core state
  const [phase, setPhase] = useState<Phase>('loading');
  const [sessionId, setSessionId] = useState<string | null>(initialSessionId);
  const [currentBackendSectionId, setCurrentBackendSectionId] = useState<string | null>(null);
  const [sessionSections, setSessionSections] = useState<MockTestSection[]>([]);
  const [currentSectionProgressionIndex, setCurrentSectionProgressionIndex] = useState(0); // Track which section in progression (0-3)


  // Per-section question state (active section)
  const [questions, setQuestions] = useState<Question[]>([]);
  const [currentQ, setCurrentQ] = useState(0);

  // Timer — starts when "Start Now" is clicked
  const [timeRemaining, setTimeRemaining] = useState(0);
  const timerRef = useRef<ReturnType<typeof setInterval> | null>(null);

  // Tracks when the current question was first shown (for 3s minimum rule)
  const questionStartTimeRef = useRef<number>(Date.now());

  // UUID shared across all sections of this test run.
  // Generated once when the page mounts — a new UUID is created every time
  // the user navigates to the test page (i.e. every "Start Test" click).
  // Use the parent session ID from custom builder if provided, so the pre-built
  // first section shares the same parent as all subsequent generated sections.
  const parentSessionIdRef = useRef<string>(initialParentSessionId ?? crypto.randomUUID());

  // Anti-cheating
  const [tabSwitchCount, setTabSwitchCount] = useState(0);
  const [showTabWarning, setShowTabWarning] = useState(false);

  // Section submit modal
  const [sectionSubmitting, setSectionSubmitting] = useState(false);
  const [answerSubmitting, setAnswerSubmitting] = useState(false);
  const [answerFeedback, setAnswerFeedback] = useState<AnswerFeedback | null>(null);
  const [loadingSection, setLoadingSection] = useState(false);

  // Init error (fatal — shown instead of spinner when session cannot be created)
  const [initError, setInitError] = useState<string | null>(null);

  // Report issue modal
  const [showReportModal, setShowReportModal] = useState(false);
  const [reportReason, setReportReason] = useState('');
  const [reportSubmitting, setReportSubmitting] = useState(false);

  // Completed section results (for transition screen)
  const [sectionResults, setSectionResults] = useState<SectionResult[]>([]);

  // Use SECTION_PROGRESSION as the source of truth for section names
  const currentSectionProgression = SECTION_PROGRESSION[currentSectionProgressionIndex];
  const currentSection = {
    section_id: currentSectionProgression?.name || 'unknown',
    section_name: currentSectionProgression ?
      currentSectionProgression.name.charAt(0).toUpperCase() + currentSectionProgression.name.slice(1)
      : 'Unknown',
    duration_minutes: currentSectionProgression?.name === 'arithmetic' || currentSectionProgression?.name === 'technical' ? 20 : 25,
    question_count: 10,
  };
  const isLastSection = currentSectionProgressionIndex === SECTION_PROGRESSION.length - 1;
  const testName = isCustomTest ? 'Custom Test' : resolveCompanyInfo(testId).name;

  // ── Sections derived from SECTION_PROGRESSION ─────────────────────────────
  const EDUCATIONAL_SECTIONS: MockTestSection[] = SECTION_PROGRESSION.map(s => ({
    section_id: s.name,
    section_name: s.name.charAt(0).toUpperCase() + s.name.slice(1),
    duration_minutes: s.name === 'arithmetic' || s.name === 'technical' ? 20 : 25,
    question_count: 10,
  }));

  type RawQ = { question_id?: number | string; question_text?: string; text?: string; options?: string[]; choices?: string[] };

  // ── Step 1: Show intro screen — no session created here
  // Sessions are created per-section when the user clicks "Start Now"
  useEffect(() => {
    const init = async () => {
      try {
        // Re-use an existing active session if one is already open for this company
        if (initialSessionId) {
          setSessionId(initialSessionId);
        } else {
          try {
            const activeSession = await getActiveSession();
            if (activeSession?.session_id && activeSession?.company_id === testId) {
              setSessionId(activeSession.session_id);
            }
          } catch {
            // No active session — fine, handleStartSection will create one
          }
        }

        setSessionSections(EDUCATIONAL_SECTIONS);
        setPhase('section_intro');
      } catch (err: unknown) {
        setInitError((err as { message?: string })?.message || 'Failed to load mock test. Please try again.');
        setPhase('loading');
      }
    };
    init();
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [testId]);


  // ── Step 2: "Start Now" — fetch real questions from backend ─────────────
  const handleStartSection = async () => {
    if (!currentSection) return;

    setLoadingSection(true);
    try {
      let backendSectionId: string;

      // Generate a fresh session per section — backend returns real questions only
      // when called with a specific category + subcategory combination.
      const sectionInfo = SECTION_PROGRESSION[currentSectionProgressionIndex];
      const activeCategory = isCustomTest && customCategories
        ? customCategories[currentSectionProgressionIndex % customCategories.length]
        : sectionInfo.name;
      const randomSubcategory = sectionInfo.subcategories[Math.floor(Math.random() * sectionInfo.subcategories.length)];

      let newSession: MockTestSession;
      try {
        newSession = await generateMockTest(testId, [activeCategory], [randomSubcategory], parentSessionIdRef.current, 180000);
      } catch (genErr: unknown) {
        const _genErr = genErr as { response?: { data?: { error_code?: string; details?: { session_id?: string } } } };
        if (_genErr?.response?.data?.error_code === 'ACTIVE_SESSION_EXISTS') {
          const existingId = _genErr.response?.data?.details?.session_id as string | undefined;
          if (existingId) {
            try { await submitTest(existingId); } catch { /* ignore close errors */ }
          }
          newSession = await generateMockTest(testId, [activeCategory], [randomSubcategory], parentSessionIdRef.current, 180000);
        } else {
          throw genErr;
        }
      }

      const newSections = newSession.sections ?? [];
      backendSectionId = newSections[0]?.section_id ?? '';

      if (!backendSectionId) {
        toast.error(`No section data for ${currentSection.section_name}. Please try again.`);
        return;
      }

      const activeSessionId = newSession.session_id;
      setSessionId(activeSessionId);
      setCurrentBackendSectionId(backendSectionId);

      let qs: RawQ[] = [];
      try {
        const raw = await getSectionQuestions(activeSessionId, backendSectionId);
        qs = Array.isArray(raw) ? raw : ((raw as { questions?: RawQ[] })?.questions ?? []);
        if (qs.length === 0) throw new Error('No questions returned from backend');
      } catch (questionsErr: unknown) {
        if ((questionsErr as { response?: { status?: number } })?.response?.status === 404) {
          toast.error('Session or section not found. Please refresh and start a new test.');
        }
        throw questionsErr;
      }

      const questions: Question[] = qs.map((q, idx) => ({
        id: q.question_id ?? idx + 1,
        section: currentSection.section_name,
        text: q.question_text ?? q.text ?? `Question ${idx + 1}`,
        options: q.options ?? q.choices ?? [],
        selected: null,
        markedForReview: false,
      }));

      if (questions.length < currentSection.question_count) {
        toast.info(`This section has ${questions.length} questions. Attempt all to proceed.`);
      }

      setQuestions(questions);
      setCurrentQ(0);
      setAnswerFeedback(null);
      setTimeRemaining((currentSection.duration_minutes ?? 30) * 60);
      setPhase('section_testing');
    } catch (err: unknown) {
      const _err = err as { response?: { status?: number; data?: { detail?: string; message?: string; error?: string } }; message?: string };
      const backendMsg = _err?.response?.data?.detail
        ?? _err?.response?.data?.message
        ?? _err?.response?.data?.error
        ?? _err?.message
        ?? 'Unknown error';
      console.error('[handleStartSection] failed:', _err?.response?.status, _err?.response?.data ?? _err?.message);
      toast.error(`Failed to load ${currentSection.section_name}: ${backendMsg}`);
    } finally {
      setLoadingSection(false);
    }
  };

  // ── Timer (runs only during section_testing) ───────────────────────────────
  useEffect(() => {
    if (phase !== 'section_testing') {
      if (timerRef.current) clearInterval(timerRef.current);
      return;
    }
    timerRef.current = setInterval(() => {
      setTimeRemaining(prev => {
        if (prev <= 1) {
          clearInterval(timerRef.current!);
          handleAutoSubmitSection();
          return 0;
        }
        return prev - 1;
      });
    }, 1000);
    return () => { if (timerRef.current) clearInterval(timerRef.current); };
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [phase]);

  // ── beforeunload warning ───────────────────────────────────────────────────
  useEffect(() => {
    const handler = (e: BeforeUnloadEvent) => {
      if (phase === 'section_testing' || phase === 'section_intro') {
        e.preventDefault();
      }
    };
    window.addEventListener('beforeunload', handler);
    return () => window.removeEventListener('beforeunload', handler);
  }, [phase]);

  // ── Tab switch detection ───────────────────────────────────────────────────
  useEffect(() => {
    const handle = () => {
      if (document.hidden && phase === 'section_testing') {
        setTabSwitchCount(p => p + 1);
        setShowTabWarning(true);
      }
    };
    document.addEventListener('visibilitychange', handle);
    return () => document.removeEventListener('visibilitychange', handle);
  }, [phase]);

  // ── Disable right-click ────────────────────────────────────────────────────
  useEffect(() => {
    const prevent = (e: MouseEvent) => { if (phase === 'section_testing') e.preventDefault(); };
    document.addEventListener('contextmenu', prevent);
    return () => document.removeEventListener('contextmenu', prevent);
  }, [phase]);

  // ── Keyboard shortcuts ─────────────────────────────────────────────────────
  useEffect(() => {
    const handle = (e: KeyboardEvent) => {
      if (phase === 'section_intro') {
        if (e.code === 'Space') { e.preventDefault(); if (!loadingSection) handleStartSection(); }
        return;
      }
      if (phase !== 'section_testing') return;
      if (e.target instanceof HTMLInputElement || e.target instanceof HTMLTextAreaElement) return;
      if (e.key === 'ArrowRight' || e.key === 'n' || e.key === 'N') handleNext();
      if (e.key === 'ArrowLeft'  || e.key === 'p' || e.key === 'P') handlePrevious();
      if (e.key === 'f' || e.key === 'F') handleMarkForReview();
      if (e.key === 's' || e.key === 'S') handleSectionSubmit();
    };
    window.addEventListener('keydown', handle);
    return () => window.removeEventListener('keydown', handle);
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [phase, currentQ, questions, loadingSection]);

  // ── Reset question start time whenever the displayed question changes ────────
  useEffect(() => {
    questionStartTimeRef.current = Date.now();
  }, [currentQ]);

  // ── Helpers ────────────────────────────────────────────────────────────────
  const formatTime = (secs: number) => {
    const m = Math.floor(secs / 60).toString().padStart(2, '0');
    const s = (secs % 60).toString().padStart(2, '0');
    return `${m}:${s}`;
  };

  const answered = questions.filter(q => q.selected !== null).length;
  const notAnswered = questions.filter(q => q.selected === null).length;
  const flagged = questions.filter(q => q.markedForReview).length;
  const currentQuestion = questions[currentQ];
  const hasNegMarking = (negMarkingSections[testId] ?? []).includes(currentSection?.section_name ?? '');

  // ── Answer handlers ────────────────────────────────────────────────────────
  const handleSelectAnswer = async (option: string) => {
    const q = questions[currentQ];
    setQuestions(prev => prev.map((item, i) =>
      i === currentQ ? { ...item, selected: option } : item
    ));

    if (!sessionId) {
      return;
    }

    // Backend requires at least 3 seconds elapsed per question.
    // Wait out any remaining time, then pass the actual elapsed seconds in the payload.
    const MIN_ANSWER_MS = 3000;
    const elapsedMs = Date.now() - questionStartTimeRef.current;
    const waitMs = Math.max(0, MIN_ANSWER_MS - elapsedMs);

    setAnswerSubmitting(true);
    setAnswerFeedback(null);
    try {
      if (waitMs > 0) {
        await new Promise(resolve => setTimeout(resolve, waitMs));
      }

      // Calculate final elapsed seconds after any wait, clamped to minimum 3
      const timeTakenSeconds = Math.max(3, Math.round((Date.now() - questionStartTimeRef.current) / 1000));

      const answerIndex = q.options.findIndex(opt => opt === option);
      let answerLetter = 'A';
      if (answerIndex >= 0) {
        answerLetter = String.fromCharCode(65 + answerIndex);
      }

      const feedback = await submitAnswer(sessionId, String(q.id), answerLetter, timeTakenSeconds);
      if (feedback) {
        setAnswerFeedback(feedback);
      }
    } catch (err: any) {
    } finally {
      setAnswerSubmitting(false);
    }
  };

  const handleClearAnswer = () => {
    setQuestions(prev => prev.map((item, i) =>
      i === currentQ ? { ...item, selected: null } : item
    ));
  };

  const handleMarkForReview = () => {
    setQuestions(prev => prev.map((item, i) =>
      i === currentQ ? { ...item, markedForReview: !item.markedForReview } : item
    ));
  };

  const handleNext = async () => {
    if (currentQ < questions.length - 1) {
      setCurrentQ(p => p + 1);
      setAnswerFeedback(null);
    }
  };

  const handlePrevious = () => {
    if (currentQ > 0) {
      setCurrentQ(p => p - 1);
      setAnswerFeedback(null);
    }
  };

  // ── Section submit ─────────────────────────────────────────────────────────
  const handleAutoSubmitSection = useCallback(async () => {
    const result: SectionResult = {
      name: currentSection.section_name,
      answered: questions.filter(q => q.selected !== null).length,
      total: questions.length,
    };
    setSectionResults(prev => [...prev, result]);

    const nextProgressionIndex = currentSectionProgressionIndex + 1;
    if (nextProgressionIndex >= SECTION_PROGRESSION.length) {
      setPhase('results_summary');
    } else {
      setCurrentSectionProgressionIndex(nextProgressionIndex);
      setQuestions([]);
      setCurrentQ(0);
      setPhase('section_intro');
    }
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [sessionId, currentBackendSectionId, currentSection, questions, currentSectionProgressionIndex]);

  const handleSectionSubmit = async () => {
    // Validate that all questions have been attempted
    const unattemptedQuestions = questions.filter(q => q.selected === null);

    if (unattemptedQuestions.length > 0) {
      toast.warning(`${unattemptedQuestions.length} question${unattemptedQuestions.length > 1 ? 's' : ''} unanswered. Answer all questions before submitting.`);
      return;
    }

    setSectionSubmitting(true);
    if (timerRef.current) clearInterval(timerRef.current);

    const result: SectionResult = {
      name: currentSection.section_name,
      answered,
      total: questions.length,
    };
    setSectionResults(prev => [...prev, result]);

    // Check if there are more sections in progression
    const nextProgressionIndex = currentSectionProgressionIndex + 1;
    if (nextProgressionIndex < SECTION_PROGRESSION.length) {
      // Move to next section intro - it will load when user clicks "Start Now"
      setCurrentSectionProgressionIndex(nextProgressionIndex);
      setQuestions([]);
      setCurrentQ(0);
      setPhase('section_intro');
    } else {
      // All sections completed - show results summary
      setPhase('results_summary');
    }

    setSectionSubmitting(false);
  };

  // ── Final test submission ──────────────────────────────────────────────────
  const finalSubmit = async () => {
    setPhase('submitting');
    try {
      await submitParentSession(parentSessionIdRef.current);
    } catch {
      // non-fatal — proceed to results even if parent submit fails
    }
    await new Promise(resolve => setTimeout(resolve, 4000));
    const resultUrl = `/mock-test/results/${testId}?parentSession=${parentSessionIdRef.current}`;
    router.push(resultUrl);
  };

  // ── Report issue ───────────────────────────────────────────────────────────
  const handleReportIssue = async () => {
    if (!reportReason.trim() || !sessionId || !currentQuestion) {
      return;
    }


    setReportSubmitting(true);
    try {
      await reportIssue(sessionId, currentQuestion.id, reportReason);

      toast.success('Issue reported. Our team will review it shortly.');
      setReportReason('');
      setShowReportModal(false);
    } catch (err: any) {

      toast.error(`Failed to report issue: ${err?.message || 'Unknown error'}`);
    } finally {
      setReportSubmitting(false);
    }
  };

  // ─────────────────────────────────────────────────────────────────────────
  // RENDER
  // ─────────────────────────────────────────────────────────────────────────

  // ── Loading ────────────────────────────────────────────────────────────────
  if (phase === 'loading') {
    if (initError) {
      return (
        <div className="w-full bg-white min-h-screen flex flex-col items-center justify-center gap-4 p-6">
          <div className="w-16 h-16 rounded-full bg-red-100 flex items-center justify-center">
            <AlertTriangle size={32} className="text-red-500" />
          </div>
          <div className="text-center max-w-md">
            <h2 className="text-xl font-bold text-slate-900 mb-2">Failed to Load Test</h2>
            <p className="text-slate-500 mb-6">{initError}</p>
            <div className="flex gap-3 justify-center">
              <button
                onClick={() => { setInitError(null); router.push('/mock-test'); }}
                className="px-5 py-2.5 border border-slate-300 text-slate-700 font-semibold rounded-lg hover:bg-slate-50 transition text-sm"
              >
                Back to Tests
              </button>
              <button
                onClick={() => { setInitError(null); window.location.reload(); }}
                className="px-5 py-2.5 bg-[#2557a7] text-white font-semibold rounded-lg hover:bg-[#1a3d73] transition text-sm"
              >
                Try Again
              </button>
            </div>
          </div>
        </div>
      );
    }
    return (
      <div className="w-full bg-white min-h-screen flex flex-col items-center justify-center gap-4">
        <div className="w-12 h-12 border-4 border-[#2557a7] border-t-transparent rounded-full animate-spin" />
        <p className="text-slate-600 font-semibold text-lg">Preparing your test...</p>
        <p className="text-slate-400 text-sm">Generating questions from the bank</p>
      </div>
    );
  }

  // ── Results Summary ───────────────────────────────────────────────────────
  if (phase === 'results_summary') {
    const totalQuestions = sectionResults.reduce((sum, r) => sum + r.total, 0);
    const totalAnswered = sectionResults.reduce((sum, r) => sum + r.answered, 0);
    const percentage = totalQuestions > 0 ? Math.round((totalAnswered / totalQuestions) * 100) : 0;

    const now    = new Date();
    const dayStr = now.toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' }).toUpperCase();
    const timeStr = now.toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit', hour12: false });

    return (
      <div className="w-full min-h-screen flex flex-col" style={{ background: '#F4F2EC' }}>

        {/* Dark top bar */}
        <div className="flex items-center justify-between px-6 py-3 shrink-0" style={{ background: '#111827' }}>
          <div className="flex items-center gap-2">
            <span className="text-xs font-semibold" style={{ color: 'rgba(255,255,255,0.5)' }}>{testName.toUpperCase()}</span>
            <span style={{ color: 'rgba(255,255,255,0.2)' }}>·</span>
            <span className="text-xs font-semibold" style={{ color: 'rgba(255,255,255,0.3)' }}>MOCK_TEST</span>
            <span style={{ color: 'rgba(255,255,255,0.2)' }}>·</span>
            <span className="text-xs font-semibold" style={{ color: 'rgba(255,255,255,0.3)' }}>SESSION {sessionId?.slice(-8).toUpperCase() ?? '—'}</span>
          </div>
          <div className="flex items-center gap-3">
            <span className="text-xs font-black tracking-widest px-2.5 py-1 rounded" style={{ background: '#374151', color: '#34d399' }}>
              COMPLETE
            </span>
            <span className="text-xs" style={{ color: 'rgba(255,255,255,0.35)' }}>{dayStr} · {timeStr} LOCAL</span>
          </div>
        </div>

        {/* Progress strip — all sections done */}
        <div className="flex items-center px-6 py-2 border-b shrink-0" style={{ background: '#1f2937', borderColor: '#374151' }}>
          <span className="text-xs font-black tracking-widest mr-5" style={{ color: 'rgba(255,255,255,0.25)' }}>TEST PROGRESSION</span>
          <div className="flex items-center flex-1 gap-1">
            {SECTION_PROGRESSION.map((sec, i, arr) => (
              <div key={sec.name} className="flex items-center gap-1">
                <div className="flex items-center gap-1.5 px-2 py-1 text-xs font-black rounded"
                  style={{ background: 'transparent', color: 'rgba(255,255,255,0.45)' }}
                >
                  <span style={{ color: 'rgba(255,255,255,0.35)', fontWeight: 900 }}>{String(i + 1).padStart(2, '0')}</span>
                  <span>{sec.name.toUpperCase()}</span>
                  <CheckCircle size={10} style={{ color: '#34d399' }} />
                </div>
                {i < arr.length - 1 && <span className="text-xs" style={{ color: 'rgba(255,255,255,0.12)' }}>·</span>}
              </div>
            ))}
          </div>
          <span className="text-xs font-black ml-4" style={{ color: '#34d399' }}>
            {String(SECTION_PROGRESSION.length).padStart(2, '0')}/{String(SECTION_PROGRESSION.length).padStart(2, '0')}
          </span>
        </div>

        {/* Section notice */}
        <div className="px-6 py-2 shrink-0 border-b" style={{ background: '#F4F2EC', borderColor: '#e5e0d5' }}>
          <span className="text-xs font-black tracking-widest" style={{ color: '#2d2d2d', opacity: 0.45 }}>
            ALL {SECTION_PROGRESSION.length} SECTIONS COMPLETE — REVIEW YOUR ATTEMPT BEFORE SUBMITTING
          </span>
        </div>

        {/* Main content: two-column */}
        <div className="flex flex-1 overflow-hidden">

          {/* Left: section breakdown table */}
          <div className="flex-1 px-10 py-8 flex flex-col overflow-y-auto">
            <h1 className="font-black mb-1" style={{ color: '#2557a7', fontSize: 32, letterSpacing: '-1px', lineHeight: 1 }}>
              Test Complete.
            </h1>
            <p className="text-sm mb-6" style={{ color: '#2d2d2d', opacity: 0.5 }}>
              All sections attempted. Submit to receive your full score report.
            </p>

            {/* Section rows */}
            <div className="flex flex-col gap-2">
              {sectionResults.map((result, idx) => {
                const pct  = result.total > 0 ? Math.round((result.answered / result.total) * 100) : 0;
                const done = result.answered === result.total;
                return (
                  <div
                    key={idx}
                    className="flex items-center gap-4 px-5 py-4 rounded-xl border"
                    style={{ background: '#ffffff', borderColor: '#e5e7eb' }}
                  >
                    <div
                      className="w-8 h-8 rounded-lg flex items-center justify-center text-xs font-black shrink-0 text-white"
                      style={{ background: '#2557a7' }}
                    >
                      {String(idx + 1).padStart(2, '0')}
                    </div>
                    <div className="flex-1 min-w-0">
                      <p className="font-black text-sm" style={{ color: '#2d2d2d' }}>{result.name.toUpperCase()}</p>
                      <p className="text-xs mt-0.5" style={{ color: 'rgba(0,0,0,0.4)' }}>
                        {result.answered} of {result.total} answered
                      </p>
                    </div>
                    {/* Mini progress bar */}
                    <div className="w-24 shrink-0">
                      <div className="w-full rounded-full overflow-hidden" style={{ height: 4, background: '#f3f4f6' }}>
                        <div
                          className="h-full rounded-full"
                          style={{ width: `${pct}%`, background: done ? '#22c55e' : '#2557a7' }}
                        />
                      </div>
                      <p className="text-xs font-black mt-1 text-right" style={{ color: done ? '#22c55e' : '#2557a7' }}>
                        {pct}%
                      </p>
                    </div>
                    <div className="shrink-0">
                      {done
                        ? <CheckCircle size={18} style={{ color: '#22c55e' }} />
                        : <span className="text-xs font-black px-2 py-1 rounded" style={{ background: '#fef3c7', color: '#92400e' }}>PARTIAL</span>
                      }
                    </div>
                  </div>
                );
              })}
            </div>

            <div className="flex-1" />

            {/* Warning */}
            <div
              className="flex items-start gap-2.5 px-4 py-3 rounded-xl border mt-6"
              style={{ background: '#fffbeb', borderColor: '#fde68a' }}
            >
              <AlertTriangle size={13} style={{ color: '#d97706', flexShrink: 0, marginTop: 1 }} />
              <p className="text-xs leading-relaxed" style={{ color: '#78350f' }}>
                Once submitted, your answers cannot be changed. Results will be available immediately after submission.
              </p>
            </div>
          </div>

          {/* Right: white summary card */}
          <div className="w-80 shrink-0 border-l flex flex-col" style={{ background: '#ffffff', borderColor: '#e5e7eb' }}>

            {/* Stat rows */}
            {[
              {
                label: 'SECTIONS',
                sub: 'all sections attempted',
                value: <span className="text-xl font-black" style={{ color: '#000' }}>{sectionResults.length} / {SECTION_PROGRESSION.length}</span>,
              },
              {
                label: 'ANSWERED',
                sub: `${totalQuestions - totalAnswered} questions skipped`,
                value: <span className="text-xl font-black" style={{ color: '#2557a7' }}>{totalAnswered}/{totalQuestions}</span>,
              },
              {
                label: 'COMPLETION',
                sub: percentage >= 100 ? 'All questions attempted' : 'Partial attempt recorded',
                value: <span className="text-xl font-black" style={{ color: percentage === 100 ? '#22c55e' : '#f59e0b' }}>{percentage}%</span>,
              },
            ].map(row => (
              <div
                key={row.label}
                className="flex items-center justify-between px-6 py-4"
                style={{ borderBottom: '1px solid #f3f4f6' }}
              >
                <div>
                  <p className="text-xs font-black tracking-wide mb-0.5" style={{ color: '#2d2d2d', opacity: 0.4 }}>{row.label}</p>
                  <p className="text-xs" style={{ color: '#2d2d2d', opacity: 0.35 }}>{row.sub}</p>
                </div>
                {row.value}
              </div>
            ))}

            <div className="flex-1" />

            {/* Submit button */}
            <div className="px-5 pt-4 pb-2">
              <button
                onClick={finalSubmit}
                className="w-full font-black py-3.5 rounded-xl text-white text-sm tracking-widest flex items-center justify-center gap-2 transition hover:opacity-90"
                style={{ background: '#2557a7' }}
              >
                <CheckCircle size={15} />
                SUBMIT FULL TEST
              </button>
            </div>

            {/* Back button */}
            <div className="px-5 pb-4">
              <button
                onClick={() => router.push('/mock-test')}
                className="w-full py-2.5 rounded-xl border text-xs font-black tracking-widest transition hover:bg-slate-50"
                style={{ borderColor: '#e5e7eb', color: '#2d2d2d', background: 'transparent' }}
              >
                BACK TO TESTS
              </button>
            </div>

            {/* Completed section pills */}
            <div className="px-5 pb-5 border-t pt-4" style={{ borderColor: '#f3f4f6' }}>
              <p className="text-xs font-black tracking-widest mb-2" style={{ color: 'rgba(0,0,0,0.25)' }}>SECTIONS COMPLETED</p>
              <div className="flex flex-wrap gap-1.5">
                {sectionResults.map((r, i) => (
                  <div
                    key={i}
                    className="flex items-center gap-1 px-2.5 py-1 rounded-full text-xs font-black"
                    style={{ background: '#eef3ff', color: '#2557a7' }}
                  >
                    <CheckCircle size={9} /> {r.name}
                  </div>
                ))}
              </div>
            </div>
          </div>
        </div>
      </div>
    );
  }

  // ── Submitting ─────────────────────────────────────────────────────────────
  if (phase === 'submitting') {
    return (
      <div className="w-full min-h-screen flex flex-col items-center justify-center gap-5" style={{ background: '#F4F2EC' }}>
        <div className="w-12 h-12 border-4 border-t-transparent rounded-full animate-spin" style={{ borderColor: '#2557a7', borderTopColor: 'transparent' }} />
        <p className="font-black text-lg tracking-wide" style={{ color: '#2557a7' }}>SCORING YOUR TEST</p>
        <p className="text-sm" style={{ color: 'rgba(0,0,0,0.4)' }}>Please wait while we calculate your results</p>
      </div>
    );
  }

  // ── Loading Next Section (removed - sections load in background) ───────────

  // ── Section Intro ──────────────────────────────────────────────────────────
  if (phase === 'section_intro') {
    const now     = new Date();
    const dayStr  = now.toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' }).toUpperCase();
    const timeStr = now.toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit', hour12: false });
    const sName   = currentSection?.section_name ?? 'Section';
    const qCount  = currentSection?.question_count ?? 10;
    const minPerQ = currentSection?.duration_minutes && qCount
      ? Math.round(currentSection.duration_minutes / qCount)
      : 2;
    const passCount = Math.ceil(qCount * 0.6);

    // Mini bar chart mock data (last 5 scores)

    return (
      <div className="w-full min-h-screen flex flex-col" style={{ background: '#F4F2EC' }}>

        {/* Dark top bar */}
        <div className="flex items-center justify-between px-6 py-3 shrink-0" style={{ background: '#111827' }}>
          <div className="flex items-center gap-2">
            <span className="text-xs font-semibold" style={{ color: 'rgba(255,255,255,0.5)' }}>{testName.toUpperCase()}</span>
            <span style={{ color: 'rgba(255,255,255,0.2)' }}>·</span>
            <span className="text-xs font-semibold" style={{ color: 'rgba(255,255,255,0.3)' }}>MOCK_TEST</span>
            <span style={{ color: 'rgba(255,255,255,0.2)' }}>·</span>
            <span className="text-xs font-semibold" style={{ color: 'rgba(255,255,255,0.3)' }}>SESSION {sessionId?.slice(-8).toUpperCase() ?? '—'}</span>
          </div>
          <div className="flex items-center gap-3">
            <span
              className="text-xs font-black tracking-widest px-2.5 py-1 rounded"
              style={{ background: '#374151', color: '#fbbf24' }}
            >
              STANDBY
            </span>
            <span className="text-xs" style={{ color: 'rgba(255,255,255,0.35)' }}>{dayStr} · {timeStr} LOCAL</span>
          </div>
        </div>

        {/* Progress strip */}
        <div
          className="flex items-center px-6 py-2 border-b shrink-0"
          style={{ background: '#1f2937', borderColor: '#374151' }}
        >
          <span className="text-xs font-black tracking-widest mr-5" style={{ color: 'rgba(255,255,255,0.25)' }}>TEST PROGRESSION</span>
          <div className="flex items-center flex-1 gap-1">
            {(sessionSections.length > 0 ? sessionSections.map((s) => ({ name: s.section_name, id: s.section_id })) : SECTION_PROGRESSION.map((s, idx) => ({ name: s.name.charAt(0).toUpperCase() + s.name.slice(1), id: String(idx) }))).map((sec, i, arr) => {
              const done   = i < currentSectionProgressionIndex;
              const active = i === currentSectionProgressionIndex;
              return (
                <div key={sec.id} className="flex items-center gap-1">
                  <div
                    className="flex items-center gap-1.5 px-2 py-1 text-xs font-black rounded"
                    style={{
                      background: active ? 'rgba(255,255,255,0.08)' : 'transparent',
                      color: active ? '#ffffff' : done ? 'rgba(255,255,255,0.45)' : 'rgba(255,255,255,0.2)',
                    }}
                  >
                    <span style={{ color: active ? '#2557a7' : done ? 'rgba(255,255,255,0.35)' : 'rgba(255,255,255,0.15)', fontWeight: 900 }}>
                      {String(i + 1).padStart(2, '0')}
                    </span>
                    <span>{sec.name.toUpperCase()}</span>
                  </div>
                  {i < arr.length - 1 && (
                    <span className="text-xs" style={{ color: 'rgba(255,255,255,0.12)' }}>·</span>
                  )}
                </div>
              );
            })}
          </div>
          <span className="text-xs font-black ml-4" style={{ color: 'rgba(255,255,255,0.25)' }}>
            {String(currentSectionProgressionIndex + 1).padStart(2, '0')}/{String(Math.max(sessionSections.length, SECTION_PROGRESSION.length)).padStart(2, '0')}
          </span>
        </div>

        {/* Section notice strip */}
        <div className="px-6 py-2 shrink-0 border-b" style={{ background: '#F4F2EC', borderColor: '#e5e0d5' }}>
          <span className="text-xs font-black tracking-widest" style={{ color: '#2d2d2d', opacity: 0.45 }}>
            ↓ SECTION {currentSectionProgressionIndex + 1} OF {sessionSections.length} — STARTING IN STANDBY
          </span>
        </div>

        {/* Main content: three-column flex row */}
        <div className="flex flex-1 gap-0 overflow-hidden">

            {/* Left: section title + description + tags */}
            <div className="flex-1 px-10 py-8 flex flex-col">
              <h1 className="font-black mb-3" style={{ color: '#2557a7', fontSize: 40, letterSpacing: '-2px', lineHeight: 1 }}>
                {sName}.
              </h1>
              <p className="text-sm mb-6 max-w-md leading-relaxed" style={{ color: '#2d2d2d', opacity: 0.6 }}>
                {sName === 'Arithmetic' && 'Number systems, percentages, profit & loss, time & work, ratios. Calculator-free. Show your work on paper.'}
                {sName === 'Aptitude'   && 'Data interpretation, averages, permutations, probability. Time-bound. Show your reasoning.'}
                {sName === 'Reasoning'  && 'Logical sequences, blood relations, directions, coding-decoding. Analytical problem solving.'}
                {sName === 'Technical'  && 'Computer science fundamentals, programming concepts, algorithms, data structures.'}
                {!['Arithmetic','Aptitude','Reasoning','Technical'].includes(sName) && `${sName} questions for ${testName}.`}
              </p>

              {/* Topic tags */}
              <div className="flex flex-wrap gap-2 mb-6">
                {getSectionTags(sName).map(tag => (
                  <span
                    key={tag}
                    className="text-xs font-medium px-3 py-1 rounded-full border"
                    style={{ background: 'transparent', borderColor: '#d1d5db', color: '#2d2d2d' }}
                  >
                    {tag.toLowerCase()}
                  </span>
                ))}
              </div>

              {/* Previously completed pills */}
              {sectionResults.length > 0 && (
                <div className="flex flex-wrap gap-2 mt-4">
                  {sectionResults.map((r, i) => (
                    <div
                      key={i}
                      className="flex items-center gap-1.5 px-3 py-1.5 rounded-full text-xs font-black"
                      style={{ background: '#eef3ff', color: '#2557a7' }}
                    >
                      <CheckCircle size={11} /> {r.name}: {r.answered}/{r.total}
                    </div>
                  ))}
                </div>
              )}

              {/* Pre-flight warning */}
              <div
                className="flex items-start gap-2.5 px-4 py-3 rounded-xl border mt-4"
                style={{ background: '#fffbeb', borderColor: '#fde68a' }}
              >
                <AlertTriangle size={13} style={{ color: '#d97706', flexShrink: 0, marginTop: 1 }} />
                <p className="text-xs leading-relaxed" style={{ color: '#78350f' }}>
                  Once you press <span className="font-black">SPACE</span>, the timer starts immediately and cannot be paused. Tab switches will be logged. Right-click is disabled until the section ends.
                </p>
              </div>

              {hasNegMarking && (
                <div
                  className="flex items-start gap-2.5 px-4 py-3 rounded-xl border mt-2"
                  style={{ background: '#fef2f2', borderColor: '#fecaca' }}
                >
                  <AlertTriangle size={13} style={{ color: '#dc2626', flexShrink: 0, marginTop: 1 }} />
                  <p className="text-xs leading-relaxed font-black" style={{ color: '#991b1b' }}>
                    NEGATIVE MARKING ACTIVE — wrong answers deduct 1/3 mark. Skip if unsure.
                  </p>
                </div>
              )}

              <div className="flex-1" />
            </div>

            {/* Right: white stats card */}
            <div className="w-96 shrink-0 border-l flex flex-col" style={{ background: '#ffffff', borderColor: '#e5e7eb' }}>

              {/* Stat rows */}
              {[
                {
                  label: 'QUESTIONS',
                  sub: 'MCQ · 4 options each',
                  value: <span className="text-xl font-black" style={{ color: '#000' }}>{qCount}</span>,
                },
                {
                  label: 'TIME',
                  sub: `${minPerQ} minutes per question avg`,
                  value: <span className="text-xl font-black" style={{ color: '#009980' }}>{String(currentSection?.duration_minutes ?? 0).padStart(2, '0')}:00</span>,
                },
                {
                  label: 'PASS MARK',
                  sub: `${passCount} of ${qCount} correct to pass`,
                  value: <span className="text-xl font-black" style={{ color: '#2557a7' }}>60%</span>,
                },
                {
                  label: 'DIFFICULTY',
                  sub: '3 easy · 5 medium · 2 hard',
                  value: (
                    <span className="text-xs font-black px-2.5 py-0.5 rounded-lg" style={{ background: '#fef3c7', color: '#92400e' }}>
                      MED
                    </span>
                  ),
                },
              ].map((row) => (
                <div
                  key={row.label}
                  className="flex items-center justify-between px-6 py-4"
                  style={{ borderBottom: '1px solid #f3f4f6' }}
                >
                  <div>
                    <p className="text-xs font-black tracking-wide mb-0.5" style={{ color: '#2d2d2d', opacity: 0.4 }}>{row.label}</p>
                    <p className="text-xs" style={{ color: '#2d2d2d', opacity: 0.35 }}>{row.sub}</p>
                  </div>
                  {row.value}
                </div>
              ))}

              {/* Begin button */}
              <div className="px-5 pt-4 pb-2">
                <button
                  onClick={handleStartSection}
                  disabled={loadingSection}
                  className="w-full font-black py-3.5 rounded-xl text-white text-sm tracking-widest flex items-center px-5 transition disabled:opacity-60"
                  style={{ background: '#2557a7' }}
                >
                  {loadingSection ? (
                    <span className="flex items-center gap-3 mx-auto">
                      <div className="w-4 h-4 border-2 border-white border-t-transparent rounded-full animate-spin" />
                      GENERATING...
                    </span>
                  ) : (
                    <>
                      <span>▶&nbsp; BEGIN {sName.toUpperCase()}</span>
                      <span
                        className="text-xs font-black px-2 py-0.5 rounded ml-auto"
                        style={{ background: 'rgba(255,255,255,0.18)', letterSpacing: '0.08em' }}
                      >
                        SPACE
                      </span>
                    </>
                  )}
                </button>
              </div>

              {/* Abort button */}
              <div className="px-5 pb-4">
                <button
                  onClick={() => router.push('/mock-test')}
                  className="w-full py-2.5 rounded-xl border text-xs font-black tracking-widest transition"
                  style={{ borderColor: '#e5e7eb', color: '#2d2d2d', background: 'transparent' }}
                >
                  ABORT TEST — RETURN TO BRIEF
                </button>
              </div>

              {sectionResults.length > 0 && (
                <div className="px-5 pb-4">
                  <button
                    onClick={() => setPhase('results_summary')}
                    className="w-full py-2 rounded-lg border text-xs font-black transition"
                    style={{ borderColor: '#e5e7eb', color: '#2d2d2d', background: 'transparent' }}
                  >
                    SKIP & VIEW RESULTS
                  </button>
                </div>
              )}
            </div>

          {/* Right narrow question navigator */}
        <div
          className="w-16 shrink-0 flex flex-col border-l overflow-hidden"
          style={{ background: '#1f2937', borderColor: '#374151' }}
        >
          {/* Session label */}
          <div className="px-2 py-2 border-b" style={{ borderColor: '#374151' }}>
            <p className="text-center font-black leading-tight" style={{ color: 'rgba(255,255,255,0.3)', fontSize: 8, letterSpacing: '0.05em' }}>
              SECTION {String(currentSectionProgressionIndex + 1).padStart(2, '0')}
            </p>
            <p className="text-center font-black truncate leading-tight mt-0.5" style={{ color: 'rgba(255,255,255,0.5)', fontSize: 8 }}>
              {sName.slice(0, 5).toUpperCase()}
            </p>
          </div>
          <div className="px-2 pt-2 pb-1 border-b" style={{ borderColor: '#374151' }}>
            <p className="text-center font-black" style={{ color: 'rgba(255,255,255,0.25)', fontSize: 8, letterSpacing: '0.05em' }}>QUESTION</p>
          </div>
          {/* Question squares (placeholders) */}
          <div className="flex-1 flex flex-col items-center py-2 gap-1.5 overflow-y-auto">
            {Array.from({ length: qCount }).map((_, i) => (
              <div
                key={i}
                className="w-8 h-8 rounded text-xs font-black flex items-center justify-center shrink-0"
                style={{ background: '#374151', color: 'rgba(255,255,255,0.35)' }}
              >
                {i + 1}
              </div>
            ))}
          </div>
          {/* Legend */}
          <div className="px-2 py-2 border-t" style={{ borderColor: '#374151' }}>
            {[
              { dot: '#374151', label: 'PRE' },
            ].map(({ dot, label }) => (
              <div key={label} className="flex items-center gap-1 mb-1">
                <div className="w-2 h-2 rounded-sm shrink-0" style={{ background: dot }} />
                <span style={{ color: 'rgba(255,255,255,0.3)', fontSize: 8, fontWeight: 700 }}>{qCount} {label}</span>
              </div>
            ))}
          </div>
        </div>
        </div>
      </div>
    );
  }

  // ── Section Testing ────────────────────────────────────────────────────────
  const isTimerWarning  = timeRemaining > 0 && timeRemaining <= 300;
  const isTimerCritical = timeRemaining > 0 && timeRemaining <= 60;

  return (
    <div className="w-full min-h-screen flex flex-col" style={{ background: '#F4F2EC' }}>
      {/* Tab switch warning */}
      <AnimatePresence>
        {showTabWarning && (
          <motion.div
            initial={{ opacity: 0, y: -60 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0, y: -60 }}
            className="fixed top-4 left-1/2 -translate-x-1/2 z-100 bg-red-600 text-white px-6 py-3 rounded-xl shadow-2xl flex items-center gap-3"
          >
            <EyeOff size={16} />
            <span className="font-semibold text-sm">Tab switch detected ({tabSwitchCount}). This is recorded.</span>
            <button onClick={() => setShowTabWarning(false)} className="ml-2 text-red-200 hover:text-white font-bold text-lg leading-none">×</button>
          </motion.div>
        )}
      </AnimatePresence>

      {/* Dark top bar */}
      <div className="flex items-center gap-3 px-4 py-3 shrink-0" style={{ background: '#111827' }}>
        {/* Section progress in top bar */}
        <div className="flex items-center gap-1 flex-1 min-w-0 overflow-hidden">
          <span className="text-xs font-semibold shrink-0 mr-1" style={{ color: 'rgba(255,255,255,0.4)' }}>{testName}</span>
          <span style={{ color: 'rgba(255,255,255,0.2)' }} className="shrink-0">·</span>
          {sessionSections.map((sec, i) => {
            const done   = i < currentSectionProgressionIndex;
            const active = i === currentSectionProgressionIndex;
            return (
              <div key={sec.section_id} className="flex items-center shrink-0">
                <span
                  className="text-xs font-black px-1"
                  style={{ color: active ? '#ffffff' : done ? '#34d399' : 'rgba(255,255,255,0.2)' }}
                >
                  {active
                    ? `${sec.section_name.toUpperCase()} ${currentQ + 1}/${questions.length}`
                    : sec.section_name.split(' ')[0].slice(0, 4).toUpperCase()}
                </span>
                {i < sessionSections.length - 1 && (
                  <span className="text-xs shrink-0" style={{ color: 'rgba(255,255,255,0.15)' }}>→</span>
                )}
              </div>
            );
          })}
        </div>

        {/* Timer */}
        <div
          className={`flex items-center gap-2 px-3 py-1.5 rounded shrink-0 ${isTimerCritical ? 'animate-pulse' : ''}`}
          style={{ background: isTimerCritical ? '#991b1b' : isTimerWarning ? '#78350f' : 'transparent' }}
        >
          <span className="text-xs font-semibold" style={{ color: isTimerWarning ? '#fbbf24' : 'rgba(255,255,255,0.4)' }}>
            TIME LEFT
          </span>
          <span
            className="font-mono font-black text-sm"
            style={{ color: isTimerCritical ? '#fca5a5' : isTimerWarning ? '#fde68a' : 'rgba(255,255,255,0.85)' }}
          >
            {formatTime(timeRemaining)}
          </span>
        </div>

        {/* Submit button */}
        <button
          onClick={handleSectionSubmit}
          disabled={sectionSubmitting}
          className="shrink-0 font-black text-xs tracking-widest px-4 py-2 rounded transition disabled:opacity-60 text-white"
          style={{ background: isLastSection ? '#059669' : '#2557a7' }}
        >
          {sectionSubmitting ? 'SUBMITTING...' : isLastSection ? 'SUBMIT TEST' : 'SUBMIT SECTION'}
        </button>
      </div>

      {/* Three-column body */}
      <div className="flex flex-1 overflow-hidden">

        {/* Left: dark question palette */}
        <div
          className="w-14 shrink-0 flex flex-col items-center py-4 gap-1.5 overflow-y-auto"
          style={{ background: '#1f2937' }}
        >
          {questions.map((q, i) => {
            const isAns     = q.selected !== null;
            const isFlagged = q.markedForReview;
            const isCurrent = i === currentQ;
            return (
              <button
                key={i}
                onClick={() => { setCurrentQ(i); setAnswerFeedback(null); }}
                className="w-8 h-8 rounded text-xs font-black flex items-center justify-center transition shrink-0"
                style={{
                  background:    isCurrent ? '#2557a7' : isFlagged ? '#f59e0b' : isAns ? '#22c55e' : '#374151',
                  color:         'white',
                  outline:       isCurrent ? '2px solid #93b4e0' : 'none',
                  outlineOffset: '1px',
                  opacity:       (!isCurrent && !isAns && !isFlagged) ? 0.6 : 1,
                }}
              >
                {i + 1}
              </button>
            );
          })}
        </div>

        {/* Center: question area */}
        <motion.div
          key={currentQ}
          initial={{ opacity: 0, x: 10 }}
          animate={{ opacity: 1, x: 0 }}
          className="flex-1 overflow-y-auto p-6"
          style={{ background: '#F4F2EC' }}
        >
          {/* Question header */}
          <div className="flex items-center gap-3 mb-5 pb-3 border-b" style={{ borderColor: '#d1d5db' }}>
            <span className="text-xs font-black tracking-widest" style={{ color: '#2d2d2d' }}>
              QUESTION {String(currentQ + 1).padStart(2, '0')}/{String(questions.length).padStart(2, '0')}
            </span>
            <span className="text-xs font-black px-2 py-0.5 rounded text-white" style={{ background: '#374151' }}>
              {currentSection?.section_name.toUpperCase()}
            </span>
            {hasNegMarking && (
              <span className="text-xs font-black px-2 py-0.5 rounded text-white" style={{ background: '#ef4444' }}>
                NEG MARK
              </span>
            )}
            {currentQuestion?.markedForReview && (
              <span className="text-xs font-black px-2 py-0.5 rounded" style={{ background: '#fef3c7', color: '#92400e' }}>
                ⭐ MARK FOR REVIEW
              </span>
            )}
            {tabSwitchCount > 0 && (
              <span className="ml-auto flex items-center gap-1 text-xs font-semibold" style={{ color: '#ef4444' }}>
                <EyeOff size={10} /> {tabSwitchCount} switch
              </span>
            )}
          </div>

          {/* Question text */}
          <div className="bg-white rounded-xl p-5 mb-5 border" style={{ borderColor: '#e5e7eb', userSelect: 'none' }}>
            <p className="text-base font-semibold leading-relaxed" style={{ color: '#000' }}>
              {currentQuestion?.text}
            </p>
          </div>

          {/* Options */}
          <div className="space-y-2.5 mb-6">
            {currentQuestion?.options.map((option, idx) => {
              const letter        = String.fromCharCode(65 + idx);
              const isSelected    = currentQuestion.selected === option;
              const correctLetter = answerFeedback?.correct_answer?.trim().charAt(0).toUpperCase();
              const correctIndex  = correctLetter ? correctLetter.charCodeAt(0) - 65 : -1;
              const isCorrect     = answerFeedback !== null && correctIndex === idx;
              const isWrong       = answerFeedback !== null && isSelected && !answerFeedback.is_correct;

              let borderColor = '#e5e7eb';
              let bgColor     = '#ffffff';
              if (answerFeedback) {
                if (isCorrect)    { borderColor = '#22c55e'; bgColor = '#f0fdf4'; }
                else if (isWrong) { borderColor = '#ef4444'; bgColor = '#fef2f2'; }
              } else if (isSelected) {
                borderColor = '#2557a7'; bgColor = '#eef3ff';
              }

              return (
                <label
                  key={idx}
                  className={`flex items-center gap-4 p-4 rounded-xl border-2 transition ${answerSubmitting ? 'cursor-not-allowed opacity-70' : 'cursor-pointer'}`}
                  style={{ borderColor, background: bgColor }}
                >
                  <span
                    className="w-7 h-7 rounded-lg flex items-center justify-center text-xs font-black shrink-0"
                    style={{
                      background: answerFeedback && isCorrect ? '#22c55e' : answerFeedback && isWrong ? '#ef4444' : isSelected ? '#2557a7' : '#f3f4f6',
                      color: (isSelected || (answerFeedback && (isCorrect || isWrong))) ? 'white' : '#2d2d2d',
                    }}
                  >
                    {letter}
                  </span>
                  <input
                    type="radio"
                    name="answer"
                    value={option}
                    checked={isSelected}
                    onChange={() => handleSelectAnswer(option)}
                    disabled={answerSubmitting || answerFeedback !== null}
                    className="sr-only"
                  />
                  <span className="flex-1 text-sm font-medium" style={{ color: '#2d2d2d' }}>{option}</span>
                  {answerFeedback && isCorrect && <CheckCircle size={15} style={{ color: '#22c55e', flexShrink: 0 }} />}
                  {answerFeedback && isWrong   && <span className="font-bold shrink-0" style={{ color: '#ef4444' }}>✗</span>}
                  {answerSubmitting && isSelected && (
                    <div className="w-4 h-4 border-2 border-t-transparent rounded-full animate-spin shrink-0" style={{ borderColor: '#2557a7' }} />
                  )}
                </label>
              );
            })}
          </div>

          {/* Action row */}
          <div className="flex items-center justify-between gap-3">
            <div className="flex items-center gap-2">
              <button
                onClick={handleMarkForReview}
                className="flex items-center gap-1.5 px-3 py-2 rounded-lg border text-xs font-black transition"
                style={{
                  borderColor: currentQuestion?.markedForReview ? '#f59e0b' : '#e5e7eb',
                  background:  currentQuestion?.markedForReview ? '#fef3c7' : 'transparent',
                  color:       currentQuestion?.markedForReview ? '#92400e' : '#2d2d2d',
                }}
              >
                <Flag size={12} /> MARK FOR REVIEW
              </button>
              {currentQuestion?.selected && (
                <button
                  onClick={handleClearAnswer}
                  className="px-3 py-2 rounded-lg border text-xs font-black transition"
                  style={{ borderColor: '#d1d5db', color: '#2d2d2d' }}
                >
                  CLEAR
                </button>
              )}
              <button
                onClick={() => setShowReportModal(true)}
                className="px-3 py-2 rounded-lg border text-xs font-black transition"
                style={{ borderColor: '#fca5a5', color: '#ef4444' }}
              >
                ⚠ REPORT
              </button>
            </div>
            <div className="flex items-center gap-2">
              <button
                onClick={handlePrevious}
                disabled={currentQ === 0}
                className="flex items-center gap-1.5 px-4 py-2 rounded-lg text-xs font-black transition disabled:opacity-40"
                style={{ border: '2px solid #d1d5db', color: '#2d2d2d' }}
              >
                <ChevronLeft size={13} /> PREVIOUS
              </button>
              <button
                onClick={handleNext}
                disabled={currentQ === questions.length - 1}
                className="flex items-center gap-1.5 px-4 py-2 rounded-lg text-xs font-black transition disabled:opacity-40 text-white"
                style={{ background: '#2557a7' }}
              >
                NEXT <ChevronRight size={13} />
              </button>
            </div>
          </div>
        </motion.div>

        {/* Right: feedback panel */}
        <div
          className="w-72 shrink-0 flex flex-col overflow-y-auto border-l"
          style={{ background: '#ffffff', borderColor: '#e5e7eb' }}
        >
          <AnimatePresence mode="wait">
            {answerFeedback ? (
              <motion.div key="feedback" initial={{ opacity: 0 }} animate={{ opacity: 1 }} className="flex-1 flex flex-col">
                <div
                  className="flex items-center gap-2 px-4 py-3"
                  style={{ background: answerFeedback.is_correct ? '#22c55e' : '#ef4444' }}
                >
                  {answerFeedback.is_correct
                    ? <CheckCircle size={15} className="text-white" />
                    : <span className="text-white font-black text-base leading-none">✗</span>
                  }
                  <span className="text-white font-black text-xs tracking-widest">
                    {answerFeedback.is_correct ? 'CORRECT' : 'INCORRECT'}
                  </span>
                  {!answerFeedback.is_correct && answerFeedback.correct_answer && (
                    <span className="ml-auto text-white text-xs opacity-80">{answerFeedback.correct_answer}</span>
                  )}
                </div>

                <div className="p-4 space-y-4 flex-1">
                  {answerFeedback.solution_steps && answerFeedback.solution_steps.length > 0 && (
                    <div>
                      <p className="text-xs font-black tracking-widest mb-2" style={{ color: '#2d2d2d', opacity: 0.45 }}>SOLUTION PATH</p>
                      <ol className="space-y-2">
                        {answerFeedback.solution_steps.map((step, i) => (
                          <li key={i} className="flex items-start gap-2 text-xs" style={{ color: '#2d2d2d' }}>
                            <span
                              className="w-4 h-4 rounded flex items-center justify-center text-xs font-black shrink-0 mt-0.5"
                              style={{ background: '#f3f4f6', color: '#2d2d2d' }}
                            >{i + 1}</span>
                            {step}
                          </li>
                        ))}
                      </ol>
                    </div>
                  )}
                  {answerFeedback.explanation && (
                    <div>
                      <p className="text-xs font-black tracking-widest mb-1" style={{ color: '#2d2d2d', opacity: 0.45 }}>EXPLANATION</p>
                      <p className="text-xs leading-relaxed whitespace-pre-line" style={{ color: '#2d2d2d' }}>
                        {answerFeedback.explanation}
                      </p>
                    </div>
                  )}
                  {answerFeedback.feedback && (
                    <div className="p-3 rounded-xl" style={{ background: '#f8faff' }}>
                      <p className="text-xs font-black tracking-widest mb-1" style={{ color: '#2d2d2d', opacity: 0.45 }}>AI PATTERN</p>
                      <p className="text-xs leading-relaxed" style={{ color: '#2d2d2d' }}>{answerFeedback.feedback}</p>
                    </div>
                  )}
                </div>
              </motion.div>
            ) : (
              <motion.div key="placeholder" initial={{ opacity: 0 }} animate={{ opacity: 1 }} className="p-4">
                <p className="text-xs font-black tracking-widest mb-1" style={{ color: '#2d2d2d', opacity: 0.45 }}>ANSWER</p>
                <p className="text-xs" style={{ color: '#2d2d2d', opacity: 0.4 }}>Select an option to see feedback</p>
              </motion.div>
            )}
          </AnimatePresence>

          {/* Section stats */}
          <div className="p-4 border-t shrink-0" style={{ borderColor: '#f3f4f6' }}>
            <p className="text-xs font-black tracking-widest mb-3" style={{ color: '#2d2d2d', opacity: 0.45 }}>THIS SECTION</p>
            <div className="grid grid-cols-3 gap-2">
              <div className="text-center p-2 rounded-xl" style={{ background: '#f0fdf4' }}>
                <div className="text-lg font-black" style={{ color: '#22c55e' }}>{answered}</div>
                <div className="text-xs font-semibold" style={{ color: '#86efac' }}>DONE</div>
              </div>
              <div className="text-center p-2 rounded-xl" style={{ background: '#f9fafb' }}>
                <div className="text-lg font-black" style={{ color: '#2d2d2d' }}>{notAnswered}</div>
                <div className="text-xs font-semibold" style={{ color: '#2d2d2d', opacity: 0.4 }}>LEFT</div>
              </div>
              <div className="text-center p-2 rounded-xl" style={{ background: '#fffbeb' }}>
                <div className="text-lg font-black" style={{ color: '#f59e0b' }}>{flagged}</div>
                <div className="text-xs font-semibold" style={{ color: '#fcd34d' }}>FLAG</div>
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* Bottom status bar */}
      <div
        className="flex items-center gap-3 px-4 py-2 border-t shrink-0 text-xs"
        style={{ background: '#1f2937', borderColor: '#374151' }}
      >
        <div className="flex items-center gap-1.5">
          <div className="w-1.5 h-1.5 rounded-full" style={{ background: '#22c55e' }} />
          <span style={{ color: 'rgba(255,255,255,0.5)' }}>NETWORK</span>
          <span style={{ color: '#22c55e' }}>OK</span>
        </div>
        <span style={{ color: 'rgba(255,255,255,0.25)' }}>·</span>
        <span style={{ color: 'rgba(255,255,255,0.5)' }}>AUTOSAVE</span>
        <span style={{ color: 'rgba(255,255,255,0.25)' }}>·</span>
        <span style={{ color: 'rgba(255,255,255,0.5)' }}>
          {String(currentQ + 1).padStart(2, '0')}/{String(questions.length).padStart(2, '0')}
        </span>
        <span style={{ color: 'rgba(255,255,255,0.25)' }}>·</span>
        <span style={{ color: '#22c55e' }}>{answered} ANSWERED</span>
        <span style={{ color: 'rgba(255,255,255,0.25)' }}>·</span>
        <span style={{ color: 'rgba(255,255,255,0.5)' }}>{notAnswered} REMAINING</span>
        {flagged > 0 && (
          <>
            <span style={{ color: 'rgba(255,255,255,0.25)' }}>·</span>
            <span style={{ color: '#f59e0b' }}>{flagged} MARK FOR REVIEW</span>
          </>
        )}
      </div>

      {/* Report issue modal */}
      {showReportModal && (
        <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50 p-4">
          <motion.div
            initial={{ opacity: 0, scale: 0.95 }}
            animate={{ opacity: 1, scale: 1 }}
            className="bg-white rounded-xl p-6 max-w-md w-full shadow-2xl"
          >
            <h2 className="text-base font-black mb-1" style={{ color: '#000' }}>Report an Issue</h2>
            <p className="text-xs mb-4" style={{ color: '#2d2d2d', opacity: 0.6 }}>Question {currentQ + 1} — describe the problem</p>
            <textarea
              value={reportReason}
              onChange={e => setReportReason(e.target.value)}
              placeholder="e.g. Wrong answer key, typo, missing option..."
              rows={4}
              className="w-full border rounded-lg px-3 py-2 text-sm outline-none resize-none mb-4"
              style={{ borderColor: '#e5e7eb' }}
            />
            <div className="flex gap-3">
              <button
                onClick={() => { setShowReportModal(false); setReportReason(''); }}
                className="flex-1 py-2 border rounded-lg text-sm font-semibold transition"
                style={{ borderColor: '#e5e7eb', color: '#2d2d2d' }}
              >
                Cancel
              </button>
              <button
                onClick={handleReportIssue}
                disabled={!reportReason.trim() || reportSubmitting}
                className="flex-1 py-2 rounded-lg text-sm font-black text-white transition disabled:opacity-50"
                style={{ background: '#ef4444' }}
              >
                {reportSubmitting ? 'Submitting...' : 'Submit Report'}
              </button>
            </div>
          </motion.div>
        </div>
      )}
    </div>
  );
}
