'use client';

import { useState, useEffect, useCallback, useRef } from 'react';
import { useRouter, useParams, useSearchParams } from 'next/navigation';
import { ChevronLeft, ChevronRight, EyeOff, AlertTriangle, CheckCircle, Star, LogOut } from 'lucide-react';
import { motion, AnimatePresence } from 'framer-motion';
import { toast } from 'sonner';
import { resolveCompanyId, resolveCompanyInfo, CATEGORY_SUBCATEGORIES } from '@/lib/mockTestConstants';
import { addSeenQuestionIds } from '@/utils/seenQuestionIds';
import { useAttemptRecorder } from '@/hooks/useAttemptRecorder';
import {
  generateMockTest,
  getSectionQuestions,
  submitAnswer,
  submitTest,
  submitParentSession,
  reportIssue,
  getActiveSession,
  isMockTestDifficulty,
  parseMockTestError,
  uploadSessionVideo,
  MockTestSection,
  MockTestSession,
  MockTestApiError,
  AnswerFeedback,
} from '@/api/mockTestApi';

// ─── Types ───────────────────────────────────────────────────────────────────

interface Question {
  id: number | string;
  section: string;
  text: string;
  options: string[];
  selected: string | null;
  markedForReview: boolean;
  // True once submitAnswer has succeeded for this question. Locked questions
  // cannot be cleared or re-selected — preserves assessment integrity once the
  // user has seen the correct answer in the feedback.
  locked: boolean;
}

type Phase = 'loading' | 'section_intro' | 'section_testing' | 'results_summary' | 'submitting';

interface SectionResult {
  /** Position in SECTION_PROGRESSION. This is the row's IDENTITY — results are
   *  upserted by it, so a section can never be recorded twice or land out of
   *  order in the Review & Submit list. */
  index: number;
  name: string;
  answered: number;
  total: number;
}

// ─── Static maps ─────────────────────────────────────────────────────────────


const negMarkingSections: Record<string, string[]> = {
  '1': ['Quantitative Aptitude', 'Reasoning Ability', 'Programming Logic'],
};



// ─── Component ───────────────────────────────────────────────────────────────

export default function MockTestPage() {
  const router = useRouter();
  const params = useParams();
  const searchParams = useSearchParams();
  const urlTestId = params.id as string;
  const initialSessionId = searchParams.get('sessionId');
  // Parent session ID pre-generated by custom builder so all sections share one parent
  const initialParentSessionId = searchParams.get('parentSessionId');

  const isCustomTest = urlTestId === 'custom-test';
  const testId = resolveCompanyId(urlTestId);

  // Custom test config from query params
  const customCategories = isCustomTest
    ? (searchParams.get('categories') ?? 'arithmetic').split(',').filter(Boolean)
    : null;
  // Optional: focus the custom test on a single subcategory/topic (e.g. when
  // launched from Weak Areas → "Practice this topic"). Falls back to a random
  // subcategory of the section's category when absent or invalid.
  const customSubcategory = isCustomTest ? searchParams.get('subcategory') : null;

  // Difficulty chosen on the setup screen (company page / custom builder / weak
  // areas), forwarded here so every section of the test generates at the level
  // the user picked. Never defaulted: the backend requires an explicit value,
  // and silently substituting 'medium' is what discarded the choice before.
  const rawDifficulty = searchParams.get('difficulty');
  const selectedDifficulty = isMockTestDifficulty(rawDifficulty) ? rawDifficulty : null;

  // Custom builder's negative-marking toggle, forwarded so the backend creates the
  // session with the penalty and deducts marks per wrong answer at scoring time.
  const negativeMarking = isCustomTest && searchParams.get('negativeMarking') === '1';

  // Section progression: Arithmetic(0) → Aptitude(1) → Reasoning(2) → Technical(3)

  const STATIC_SECTION_PROGRESSION = [
    { name: 'arithmetic', subcategories: CATEGORY_SUBCATEGORIES['arithmetic'] },
    { name: 'aptitude',   subcategories: CATEGORY_SUBCATEGORIES['aptitude'] },
    { name: 'reasoning',  subcategories: CATEGORY_SUBCATEGORIES['reasoning'] },
    { name: 'technical',  subcategories: CATEGORY_SUBCATEGORIES['technical'] },
  ];

  const SECTION_PROGRESSION = isCustomTest && customCategories && customCategories.length > 0
    ? customCategories.map(cat => ({
        name: cat,
        subcategories: CATEGORY_SUBCATEGORIES[cat] ?? [cat],
      }))
    : STATIC_SECTION_PROGRESSION;

  // Core state
  const [phase, setPhase] = useState<Phase>('loading');
  const [sessionId, setSessionId] = useState<string | null>(initialSessionId);
  const [currentBackendSectionId, setCurrentBackendSectionId] = useState<string | null>(null);
  const [currentSectionProgressionIndex, setCurrentSectionProgressionIndex] = useState(0); // Track which section in progression (0-3)


  // Per-section question state (active section)
  const [questions, setQuestions] = useState<Question[]>([]);
  // Always-current mirror of `questions`. The timer's auto-submit closure is created
  // once per section (effect dep [phase]) and would otherwise capture a stale snapshot
  // where every answer is still unselected — recording "0 answered" even though the
  // answers were saved to the backend. Reading the ref avoids that staleness.
  const questionsRef = useRef<Question[]>([]);
  questionsRef.current = questions;
  const [currentQ, setCurrentQ] = useState(0);

  // Timer — starts when "Start Now" is clicked
  const [timeRemaining, setTimeRemaining] = useState(0);
  const timerRef = useRef<ReturnType<typeof setInterval> | null>(null);

  // Tracks when the current question was first shown (for 3s minimum rule)
  const questionStartTimeRef = useRef<number>(Date.now());

  // UUID shared across all sections of this test run.
  // Generated once when the page mounts — a new UUID is created every time
  // the user navigates to the test page (i.e. every "Start Test" click).
  // Use the parent session ID from custom builder if provided, so the pre-built
  // first section shares the same parent as all subsequent generated sections.
  const parentSessionIdRef = useRef<string>(initialParentSessionId ?? crypto.randomUUID());

  // Anti-cheating
  const [tabSwitchCount, setTabSwitchCount] = useState(0);
  const [showTabWarning, setShowTabWarning] = useState(false);

  // Section submit modal
  const [sectionSubmitting, setSectionSubmitting] = useState(false);
  // Per-question state, keyed by question id. These MUST NOT be global: a single
  // shared flag meant that while one question's answer was mid-submit (it waits out
  // a 3s backend minimum, then a network round-trip), navigating to another question
  // showed that question's options as disabled/"frozen" and could flash the wrong
  // question's feedback. Keying by id isolates each question.
  const [submittingIds, setSubmittingIds] = useState<Set<string>>(new Set());
  const [feedbackByQ, setFeedbackByQ] = useState<Record<string, AnswerFeedback>>({});
  const [loadingSection, setLoadingSection] = useState(false);

  // Init error (fatal — shown instead of spinner when session cannot be created)
  const [initError, setInitError] = useState<string | null>(null);

  // Why a section failed to start. Persisted (rather than only toasted) because
  // the common cause is running out of credits, which the user has to act on —
  // a toast that fades after 4s left the intro screen looking simply broken.
  const [sectionError, setSectionError] = useState<MockTestApiError | null>(null);

  // Why the final "Submit Full Test" failed, shown on the Review & Submit screen
  // so a failed submission is visible and retryable instead of silent.
  const [finalSubmitError, setFinalSubmitError] = useState<string | null>(null);

  // ── Proctoring: webcam recording of the attempt ──────────────────────────
  // Camera access is REQUIRED to start a section. The recording spans the whole
  // attempt (it keeps running across section intros) and is uploaded to
  // /mock-test/{session}/video-evaluation once the test is submitted.
  const recorder = useAttemptRecorder();

  // Report issue modal
  const [showReportModal, setShowReportModal] = useState(false);
  const [reportReason, setReportReason] = useState('');
  const [reportSubmitting, setReportSubmitting] = useState(false);

  // Mid-test exit modal
  const [showExitConfirm, setShowExitConfirm] = useState(false);
  const [exitSubmitting, setExitSubmitting] = useState(false);

  // Completed section results (for transition screen)
  const [sectionResults, setSectionResults] = useState<SectionResult[]>([]);

  // Every section — company and custom — is a flat 10 questions / 20 minutes.
  const perSectionCount = 10;
  const perSectionMinutes = 20;
  const questionCountFor = (_sectionIdx: number): number => perSectionCount;

  // Use SECTION_PROGRESSION as the source of truth for section names
  const currentSectionProgression = SECTION_PROGRESSION[currentSectionProgressionIndex];
  const currentSection = {
    section_id: currentSectionProgression?.name || 'unknown',
    section_name: currentSectionProgression ?
      currentSectionProgression.name.charAt(0).toUpperCase() + currentSectionProgression.name.slice(1)
      : 'Unknown',
    duration_minutes: perSectionMinutes,
    question_count: questionCountFor(currentSectionProgressionIndex),
  };
  const isLastSection = currentSectionProgressionIndex === SECTION_PROGRESSION.length - 1;
  const testName = isCustomTest ? 'Custom Test' : resolveCompanyInfo(testId).name;

  // ── Sections derived from SECTION_PROGRESSION ─────────────────────────────
  const EDUCATIONAL_SECTIONS: MockTestSection[] = SECTION_PROGRESSION.map((s, idx) => ({
    section_id: s.name,
    section_name: s.name.charAt(0).toUpperCase() + s.name.slice(1),
    duration_minutes: perSectionMinutes,
    question_count: questionCountFor(idx),
  }));

  type RawQ = { question_id?: number | string; question_text?: string; text?: string; options?: string[]; choices?: string[] };

  // ── Step 1: Show intro screen — no session created here
  // Sessions are created per-section when the user clicks "Start Now"
  useEffect(() => {
    const init = async () => {
      try {
        // Re-use an existing active session if one is already open for this company
        if (initialSessionId) {
          setSessionId(initialSessionId);
        } else {
          try {
            const activeSession = await getActiveSession();
            if (activeSession?.session_id && activeSession?.company_id === testId) {
              setSessionId(activeSession.session_id);
            }
          } catch {
            // No active session — fine, handleStartSection will create one
          }
        }

        setPhase('section_intro');
      } catch (err: unknown) {
        setInitError((err as { message?: string })?.message || 'Failed to load mock test. Please try again.');
        setPhase('loading');
      }
    };
    init();
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [testId]);


  // ── Step 2: "Start Now" — fetch real questions from backend ─────────────
  const handleStartSection = async () => {
    if (!currentSection) return;

    // The backend requires an explicit difficulty. If we got here without one
    // (hand-edited or stale URL), send the user back to pick rather than
    // quietly generating a 'medium' test they never asked for.
    if (!selectedDifficulty) {
      toast.error('No difficulty selected. Please start the test again from the setup screen.');
      return;
    }

    // Enter fullscreen — must run synchronously from the user-gesture click,
    // before any awaits, or the browser strips the gesture context.
    if (typeof document !== 'undefined' && !document.fullscreenElement) {
      document.documentElement.requestFullscreen().catch(() => { /* denied or unsupported */ });
    }

    // Proctoring gate: the camera is REQUIRED. Started here, still inside the
    // click gesture, and only once — the recording continues across every
    // section so the upload covers the whole attempt rather than the last part.
    // A refusal aborts the section instead of silently running unproctored.
    if (!recorder.isRecording) {
      try {
        await recorder.start();
      } catch (camErr: unknown) {
        const message = (camErr as { message?: string })?.message
          ?? 'Camera access is required to start this proctored test.';
        setSectionError({ message, insufficientCredits: false });
        toast.error(message);
        return;
      }
    }

    setLoadingSection(true);
    setSectionError(null);
    try {
      let backendSectionId: string;

      // Generate a fresh session per section — backend returns real questions only
      // when called with a specific category + subcategory combination.
      const sectionInfo = SECTION_PROGRESSION[currentSectionProgressionIndex];
      const activeCategory = isCustomTest && customCategories
        ? customCategories[currentSectionProgressionIndex % customCategories.length]
        : sectionInfo.name;
      // Prefer the focused subcategory (from Weak Areas) when it's valid for
      // this section's category; otherwise pick a random one.
      const chosenSubcategory = (customSubcategory && sectionInfo.subcategories.includes(customSubcategory))
        ? customSubcategory
        : sectionInfo.subcategories[Math.floor(Math.random() * sectionInfo.subcategories.length)];

      let newSession: MockTestSession;
      try {
        newSession = await generateMockTest(testId, [activeCategory], [chosenSubcategory], selectedDifficulty, parentSessionIdRef.current, 180000, currentSection.question_count, currentSection.duration_minutes, negativeMarking);
      } catch (genErr: unknown) {
        const _genErr = genErr as { response?: { data?: { error_code?: string; details?: { session_id?: string } } } };
        if (_genErr?.response?.data?.error_code === 'ACTIVE_SESSION_EXISTS') {
          const existingId = _genErr.response?.data?.details?.session_id as string | undefined;
          if (existingId) {
            try { await submitTest(existingId); } catch { /* ignore close errors */ }
          }
          newSession = await generateMockTest(testId, [activeCategory], [chosenSubcategory], selectedDifficulty, parentSessionIdRef.current, 180000, currentSection.question_count, currentSection.duration_minutes, negativeMarking);
        } else {
          throw genErr;
        }
      }

      const newSections = newSession.sections ?? [];
      backendSectionId = newSections[0]?.section_id ?? '';

      if (!backendSectionId) {
        toast.error(`No section data for ${currentSection.section_name}. Please try again.`);
        return;
      }

      const activeSessionId = newSession.session_id;
      setSessionId(activeSessionId);
      setCurrentBackendSectionId(backendSectionId);

      let qs: RawQ[] = [];
      try {
        const raw = await getSectionQuestions(activeSessionId, backendSectionId);
        qs = Array.isArray(raw) ? raw : ((raw as { questions?: RawQ[] })?.questions ?? []);
        if (qs.length === 0) throw new Error('No questions returned from backend');
      } catch (questionsErr: unknown) {
        if ((questionsErr as { response?: { status?: number } })?.response?.status === 404) {
          toast.error('Session or section not found. Please refresh and start a new test.');
        }
        throw questionsErr;
      }

      const questions: Question[] = qs.map((q, idx) => ({
        id: q.question_id ?? idx + 1,
        section: currentSection.section_name,
        text: q.question_text ?? q.text ?? `Question ${idx + 1}`,
        options: q.options ?? q.choices ?? [],
        selected: null,
        markedForReview: false,
        locked: false,
      }));

      // Record the question IDs the user is about to see so the next
      // /mock-test/generate call for this company excludes them and the
      // user doesn't get the same questions on a retake.
      addSeenQuestionIds(testId, qs.map(q => q.question_id ?? null));

      if (questions.length < currentSection.question_count) {
        toast.info(`This section has ${questions.length} questions. Attempt all to proceed.`);
      }

      setQuestions(questions);
      setCurrentQ(0);
      // Fresh section — drop any per-question feedback/submitting state from the
      // previous one so nothing carries over.
      setFeedbackByQ({});
      setSubmittingIds(new Set());
      setTimeRemaining((currentSection.duration_minutes ?? 30) * 60);
      setPhase('section_testing');
    } catch (err: unknown) {
      const _err = err as { response?: { status?: number; data?: unknown }; message?: string };
      // parseMockTestError unwraps the { error: { message, details } } envelope.
      // Reading `data.error` directly used to yield an object, so every failure —
      // including a routine out-of-credits 402 — surfaced as "[object Object]".
      const parsed = parseMockTestError(err);
      console.error('[handleStartSection] failed:', _err?.response?.status, _err?.response?.data ?? _err?.message);
      setSectionError(parsed);
      toast.error(
        parsed.insufficientCredits
          ? parsed.message
          : `Failed to load ${currentSection.section_name}: ${parsed.message}`
      );
    } finally {
      setLoadingSection(false);
    }
  };

  // ── Timer (runs only during section_testing) ───────────────────────────────
  useEffect(() => {
    if (phase !== 'section_testing') {
      if (timerRef.current) clearInterval(timerRef.current);
      return;
    }
    // The updater stays PURE — it only decrements. Auto-submit used to be called
    // from inside it, but React treats updaters as replayable and may invoke them
    // more than once, which could fire the submit (and its setSectionResults)
    // twice for a single section. The expiry is handled by its own effect below.
    timerRef.current = setInterval(() => {
      setTimeRemaining(prev => (prev <= 1 ? 0 : prev - 1));
    }, 1000);
    return () => { if (timerRef.current) clearInterval(timerRef.current); };
  }, [phase]);

  // ── beforeunload warning ───────────────────────────────────────────────────
  useEffect(() => {
    const handler = (e: BeforeUnloadEvent) => {
      if (phase === 'section_testing' || phase === 'section_intro') {
        e.preventDefault();
      }
    };
    window.addEventListener('beforeunload', handler);
    return () => window.removeEventListener('beforeunload', handler);
  }, [phase]);

  // ── Lockdown: tab-switch / window-blur detection ───────────────────────────
  // The browser cannot truly block OS-level Alt-Tab or new-tab shortcuts;
  // we detect focus loss during testing and force the user to acknowledge it
  // via the blocking modal below.
  useEffect(() => {
    if (phase !== 'section_testing') return;
    const flag = () => {
      setTabSwitchCount(p => p + 1);
      setShowTabWarning(true);
    };
    const onVisibility = () => { if (document.hidden) flag(); };
    const onBlur = () => flag();
    const onFullscreenChange = () => { if (!document.fullscreenElement) flag(); };

    document.addEventListener('visibilitychange', onVisibility);
    window.addEventListener('blur', onBlur);
    document.addEventListener('fullscreenchange', onFullscreenChange);
    return () => {
      document.removeEventListener('visibilitychange', onVisibility);
      window.removeEventListener('blur', onBlur);
      document.removeEventListener('fullscreenchange', onFullscreenChange);
    };
  }, [phase]);

  // ── Exit fullscreen when the test ends or the page unmounts ────────────────
  useEffect(() => {
    if (phase === 'results_summary' && typeof document !== 'undefined' && document.fullscreenElement) {
      document.exitFullscreen().catch(() => {});
    }
  }, [phase]);

  useEffect(() => {
    return () => {
      if (typeof document !== 'undefined' && document.fullscreenElement) {
        document.exitFullscreen().catch(() => {});
      }
    };
  }, []);

  // ── Disable right-click ────────────────────────────────────────────────────
  useEffect(() => {
    const prevent = (e: MouseEvent) => { if (phase === 'section_testing') e.preventDefault(); };
    document.addEventListener('contextmenu', prevent);
    return () => document.removeEventListener('contextmenu', prevent);
  }, [phase]);

  // ── Escape closes whichever modal is open ──────────────────────────────────
  useEffect(() => {
    const onKey = (e: KeyboardEvent) => {
      if (e.key !== 'Escape') return;
      if (showReportModal) { setShowReportModal(false); return; }
      if (showExitConfirm) { setShowExitConfirm(false); return; }
      if (showTabWarning)  { setShowTabWarning(false);  return; }
    };
    document.addEventListener('keydown', onKey);
    return () => document.removeEventListener('keydown', onKey);
  }, [showReportModal, showExitConfirm, showTabWarning]);

  // ── Block copy / paste / cut while testing ────────────────────────────────
  useEffect(() => {
    if (phase !== 'section_testing') return;
    const block = (e: ClipboardEvent) => e.preventDefault();
    document.addEventListener('copy',  block);
    document.addEventListener('paste', block);
    document.addEventListener('cut',   block);
    return () => {
      document.removeEventListener('copy',  block);
      document.removeEventListener('paste', block);
      document.removeEventListener('cut',   block);
    };
  }, [phase]);

  // ── Keyboard shortcuts ─────────────────────────────────────────────────────
  useEffect(() => {
    const handle = (e: KeyboardEvent) => {
      if (phase === 'section_intro') {
        if (e.code === 'Space') { e.preventDefault(); if (!loadingSection) handleStartSection(); }
        return;
      }
      if (phase !== 'section_testing') return;

      // Block clipboard / browser-action shortcuts during the test:
      //   Ctrl/Cmd + C / V / X / A / P / S / U   (copy, paste, cut, select-all, print, save, view-source)
      //   F12 and Ctrl+Shift+I/J/C               (DevTools)
      // OS-level shortcuts (Alt+Tab, Ctrl+T, Ctrl+W, Windows key) cannot be
      // blocked from a web page — browsers reserve them. Tab-switch / focus-loss
      // detection above catches those cases instead.
      const k = e.key.toLowerCase();
      if ((e.ctrlKey || e.metaKey) && ['c', 'v', 'x', 'a', 'p', 's', 'u'].includes(k)) {
        e.preventDefault();
        return;
      }
      if (e.key === 'F12' || ((e.ctrlKey || e.metaKey) && e.shiftKey && ['i', 'j', 'c'].includes(k))) {
        e.preventDefault();
        return;
      }

      if (e.target instanceof HTMLInputElement || e.target instanceof HTMLTextAreaElement) return;
      if (e.key === 'ArrowRight' || e.key === 'n' || e.key === 'N') handleNext();
      if (e.key === 'ArrowLeft'  || e.key === 'p' || e.key === 'P') handlePrevious();
      if (e.key === 'f' || e.key === 'F') handleMarkForReview();
      if (e.key === 's' || e.key === 'S') handleSectionSubmit();
    };
    window.addEventListener('keydown', handle);
    return () => window.removeEventListener('keydown', handle);
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [phase, currentQ, questions, loadingSection]);

  // ── Reset question start time whenever the displayed question changes ────────
  useEffect(() => {
    questionStartTimeRef.current = Date.now();
  }, [currentQ]);

  // ── Helpers ────────────────────────────────────────────────────────────────
  const formatTime = (secs: number) => {
    const m = Math.floor(secs / 60).toString().padStart(2, '0');
    const s = (secs % 60).toString().padStart(2, '0');
    return `${m}:${s}`;
  };

  const answered = questions.filter(q => q.selected !== null).length;
  const notAnswered = questions.filter(q => q.selected === null).length;
  const flagged = questions.filter(q => q.markedForReview).length;
  const currentQuestion = questions[currentQ];
  // Derived from the per-question maps so the rest of the render can keep using
  // `answerFeedback` / `answerSubmitting` unchanged — but now they reflect ONLY
  // the question on screen, never another question's in-flight submit.
  const currentQId = currentQuestion ? String(currentQuestion.id) : '';
  const answerFeedback: AnswerFeedback | null = feedbackByQ[currentQId] ?? null;
  const answerSubmitting = submittingIds.has(currentQId);
  const hasNegMarking = (negMarkingSections[testId] ?? []).includes(currentSection?.section_name ?? '');

  // ── Answer handlers ────────────────────────────────────────────────────────
  const handleSelectAnswer = async (option: string) => {
    const q = questions[currentQ];
    // Defense in depth: ignore selections on a question that already got a
    // verdict from the backend. The radio/label is also disabled in the UI.
    if (q?.locked) return;
    // Lock immediately on selection. The answer is final and stays locked when
    // navigating Prev/Next. Locking up-front (instead of after the async submit)
    // makes it immune to backend/network failures — a failed submitAnswer below
    // can no longer leave the question editable.
    setQuestions(prev => prev.map((item, i) =>
      i === currentQ ? { ...item, selected: option, locked: true } : item
    ));

    if (!sessionId) {
      return;
    }

    // Backend requires at least 3 seconds elapsed per question.
    // Wait out any remaining time, then pass the actual elapsed seconds in the payload.
    const MIN_ANSWER_MS = 3000;
    const elapsedMs = Date.now() - questionStartTimeRef.current;
    const waitMs = Math.max(0, MIN_ANSWER_MS - elapsedMs);

    const qId = String(q.id);
    setSubmittingIds(prev => new Set(prev).add(qId));
    try {
      if (waitMs > 0) {
        await new Promise(resolve => setTimeout(resolve, waitMs));
      }

      // Calculate final elapsed seconds after any wait, clamped to minimum 3
      const timeTakenSeconds = Math.max(3, Math.round((Date.now() - questionStartTimeRef.current) / 1000));

      const answerIndex = q.options.findIndex(opt => opt === option);
      let answerLetter = 'A';
      if (answerIndex >= 0) {
        answerLetter = String.fromCharCode(65 + answerIndex);
      }

      const feedback = await submitAnswer(sessionId, qId, answerLetter, timeTakenSeconds);
      if (feedback) {
        setFeedbackByQ(prev => ({ ...prev, [qId]: feedback }));
      }
    } catch {
      // Answer is already locked; a failed submit leaves it recorded locally and
      // is reconciled at section submit. Nothing to surface to the user here.
    } finally {
      setSubmittingIds(prev => {
        const next = new Set(prev);
        next.delete(qId);
        return next;
      });
    }
  };

  const handleClearAnswer = () => {
    // Locked questions cannot be cleared — once the backend has returned a
    // verdict (and revealed the correct answer), the selection is final.
    if (questions[currentQ]?.locked) return;
    setQuestions(prev => prev.map((item, i) =>
      i === currentQ ? { ...item, selected: null } : item
    ));
  };

  const handleMarkForReview = () => {
    setQuestions(prev => prev.map((item, i) =>
      i === currentQ ? { ...item, markedForReview: !item.markedForReview } : item
    ));
  };

  const handleNext = async () => {
    if (currentQ < questions.length - 1) {
      setCurrentQ(p => p + 1);
    }
  };

  const handlePrevious = () => {
    if (currentQ > 0) {
      setCurrentQ(p => p - 1);
    }
  };

  // ── Mid-test exit: best-effort close the active session, then go to dashboard.
  const handleExitTest = async () => {
    setExitSubmitting(true);
    try {
      if (sessionId) {
        await submitTest(sessionId).catch(() => { /* ignore — we're abandoning */ });
      }
    } finally {
      // Reset phase so the page-unload guard (beforeunload) and fullscreen
      // cleanup don't fight the navigation.
      setPhase('loading');
      router.push('/dashboard');
    }
  };

  // ── Section submit ─────────────────────────────────────────────────────────

  /**
   * Record one section's outcome, keyed by its position in SECTION_PROGRESSION.
   *
   * Upsert, not append. The previous code pushed unconditionally, so anything
   * that ran the submit path twice for one section (timer expiry racing a manual
   * submit, a held-down "S" key repeating keydown, a double-click) added a second
   * row. Review & Submit then listed 5+ rows for a 4-section test, with the extra
   * one showing a partial count — which is exactly the "not all sections at 100%"
   * report. Keying by index makes a repeat submission a no-op overwrite.
   */
  /** Index of the section already submitted, so a repeat submit is a no-op. */
  const submitLatchRef = useRef<number | null>(null);

  const recordSectionResult = useCallback((index: number, name: string, qs: Question[]) => {
    const result: SectionResult = {
      index,
      name,
      answered: qs.filter(q => q.selected !== null).length,
      total: qs.length,
    };
    setSectionResults(prev => [...prev.filter(r => r.index !== index), result].sort((a, b) => a.index - b.index));
  }, []);

  const advanceAfterSection = useCallback((fromIndex: number) => {
    const nextProgressionIndex = fromIndex + 1;
    if (nextProgressionIndex >= SECTION_PROGRESSION.length) {
      setPhase('results_summary');
    } else {
      setCurrentSectionProgressionIndex(nextProgressionIndex);
      setQuestions([]);
      setCurrentQ(0);
      setPhase('section_intro');
    }
  }, [SECTION_PROGRESSION.length]);

  const handleAutoSubmitSection = useCallback(async () => {
    // Read the latest questions from the ref — the timer closure that calls this is
    // created at section start and would otherwise see a stale, all-unanswered snapshot.
    recordSectionResult(currentSectionProgressionIndex, currentSection.section_name, questionsRef.current);
    advanceAfterSection(currentSectionProgressionIndex);
  }, [currentSection, currentSectionProgressionIndex, recordSectionResult, advanceAfterSection]);

  // Timer expiry → auto-submit. Lives here rather than inside the interval's
  // state updater so it runs exactly once per section. The ref latch also stops a
  // re-render at timeRemaining === 0 from submitting the same section again.
  const autoSubmittedForRef = useRef<number | null>(null);
  useEffect(() => {
    if (phase !== 'section_testing') return;
    if (timeRemaining !== 0) return;
    if (autoSubmittedForRef.current === currentSectionProgressionIndex) return;
    autoSubmittedForRef.current = currentSectionProgressionIndex;
    handleAutoSubmitSection();
  // handleAutoSubmitSection is intentionally omitted: it depends on currentSection,
  // which is rebuilt every render, so including it would re-run this effect on every
  // render. The expiry condition + ref latch above are what gate the call.
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [phase, timeRemaining, currentSectionProgressionIndex]);

  const handleSectionSubmit = async () => {
    // Re-entrancy latch. A ref, not the `sectionSubmitting` state: that state is
    // set and cleared inside this same function, so a second call would still read
    // the pre-render value and sail straight through. A held "S" key repeats
    // keydown, and the disabled button only disables after a re-render.
    if (submitLatchRef.current === currentSectionProgressionIndex) return;

    // Refuse to record a section that has no questions loaded. Without this the
    // "all answered" check below silently passes — filtering an empty array
    // yields an empty array — and the section is recorded as 0 answered of 0,
    // which renders on Review & Submit as "Skipped / 0%" even though the user
    // never had anything to answer. That is indistinguishable from the reported
    // "section shows an incorrect completion percentage".
    if (questions.length === 0) {
      toast.error('This section has no questions loaded. Please restart the section.');
      return;
    }

    // Validate that all questions have been attempted
    const unattemptedQuestions = questions.filter(q => q.selected === null);

    if (unattemptedQuestions.length > 0) {
      toast.warning(`${unattemptedQuestions.length} question${unattemptedQuestions.length > 1 ? 's' : ''} unanswered. Answer all questions before submitting.`);
      return;
    }

    submitLatchRef.current = currentSectionProgressionIndex;
    setSectionSubmitting(true);
    if (timerRef.current) clearInterval(timerRef.current);

    recordSectionResult(currentSectionProgressionIndex, currentSection.section_name, questions);
    advanceAfterSection(currentSectionProgressionIndex);

    setSectionSubmitting(false);
  };

  // ── Final test submission ──────────────────────────────────────────────────
  const finalSubmitLatchRef = useRef(false);

  const finalSubmit = async () => {
    // Re-entrancy latch. Without it a second click started a second submit and a
    // second delayed navigation.
    if (finalSubmitLatchRef.current) return;
    finalSubmitLatchRef.current = true;

    setFinalSubmitError(null);
    setPhase('submitting');

    // Stop the proctoring recording BEFORE submitting, so the camera light goes
    // out as soon as the test is over and the blob is ready to upload.
    let attemptVideo: Blob | null = null;
    try {
      attemptVideo = await recorder.stop();
    } catch (recErr) {
      console.error('[finalSubmit] could not finalise recording:', recErr);
    }

    try {
      await submitParentSession(parentSessionIdRef.current);
    } catch (err: unknown) {
      // Previously this was a bare `catch {}` that swallowed EVERY failure and
      // navigated on regardless — so a failed submit looked like a dead button:
      // the user waited on a spinner, landed on a results page that could not
      // load, and was never told the report had not been submitted.
      const parsed = parseMockTestError(err);
      console.error('[finalSubmit] parent submit failed:', err);
      finalSubmitLatchRef.current = false;
      setFinalSubmitError(parsed.message);
      setPhase('results_summary');   // hand the screen back so they can retry
      toast.error(`Could not submit your test: ${parsed.message}`);
      return;
    }

    // Upload the proctoring recording WITHOUT awaiting it.
    //
    // This used to block the navigation below. Reaching 100% only means the bytes
    // are sent — the backend then forwards the file to the AI evaluator, which is
    // allowed up to 600s for a long recording. So the user sat on
    // "Uploading proctoring recording — 100%" for minutes before their results
    // appeared, for a file that has no bearing on their score.
    //
    // A client-side route change does not tear down an in-flight XHR, so the
    // upload carries on after we navigate and reports its outcome by toast.
    // A header-only blob is not a playable video and the evaluator will reject it
    // as corrupt, so don't spend an upload on it — say what happened instead.
    const MIN_PLAUSIBLE_VIDEO_BYTES = 16 * 1024;
    if (attemptVideo && attemptVideo.size > 0 && attemptVideo.size < MIN_PLAUSIBLE_VIDEO_BYTES) {
      console.error('[finalSubmit] recording too small to be valid', {
        bytes: attemptVideo.size, type: attemptVideo.type,
      });
      toast.warning('The proctoring recording was too short to be saved. Your answers were submitted and scored.');
    } else if (attemptVideo && attemptVideo.size > 0) {
      const sizeMb = Math.max(1, Math.round(attemptVideo.size / (1024 * 1024)));
      // Logged so a rejection can be tied to the exact container and size produced.
      console.info('[finalSubmit] uploading recording', {
        bytes: attemptVideo.size, type: attemptVideo.type, extension: recorder.fileExtension,
      });
      toast.info(`Uploading your ${sizeMb} MB proctoring recording in the background.`);
      void uploadSessionVideo(
        parentSessionIdRef.current,          // backend resolves parent → child session
        attemptVideo,
        `attempt-${parentSessionIdRef.current}${recorder.fileExtension}`,
      )
        .then(() => toast.success('Proctoring recording uploaded.'))
        .catch((videoErr: unknown) => {
          console.error('[finalSubmit] proctoring upload failed:', videoErr);
          toast.warning(
            `Your answers were submitted and scored, but the proctoring recording could not be uploaded: ${parseMockTestError(videoErr).message}`,
          );
        });
    }

    // No artificial delay. The old code slept 4s before navigating, which made a
    // ~60ms submit feel broken. The results page already polls while the backend
    // finishes scoring, so there is nothing to wait for here.
    const resultUrl = `/mock-test/results/${testId}?parentSession=${parentSessionIdRef.current}`;
    router.push(resultUrl);
  };

  // ── Report issue ───────────────────────────────────────────────────────────
  const handleReportIssue = async () => {
    if (!reportReason.trim() || !sessionId || !currentQuestion) {
      return;
    }


    setReportSubmitting(true);
    try {
      await reportIssue(sessionId, currentQuestion.id, reportReason);

      toast.success('Issue reported. Our team will review it shortly.');
      setReportReason('');
      setShowReportModal(false);
    } catch (err: any) {

      toast.error(`Failed to report issue: ${err?.message || 'Unknown error'}`);
    } finally {
      setReportSubmitting(false);
    }
  };

  // ─────────────────────────────────────────────────────────────────────────
  // RENDER
  // ─────────────────────────────────────────────────────────────────────────

  // ── Loading ────────────────────────────────────────────────────────────────
  if (phase === 'loading') {
    if (initError) {
      return (
        <div className="w-full bg-white min-h-screen flex flex-col items-center justify-center gap-4 p-6">
          <div className="w-16 h-16 rounded-full bg-red-100 flex items-center justify-center">
            <AlertTriangle size={32} className="text-red-500" />
          </div>
          <div className="text-center max-w-md">
            <h2 className="text-xl font-bold text-slate-900 mb-2">Failed to Load Test</h2>
            <p className="text-slate-500 mb-6">{initError}</p>
            <div className="flex gap-3 justify-center">
              <button
                onClick={() => { setInitError(null); router.push('/mock-test'); }}
                className="px-5 py-2.5 border border-slate-300 text-slate-700 font-semibold rounded-lg hover:bg-slate-50 transition text-sm"
              >
                Back to Tests
              </button>
              <button
                onClick={() => { setInitError(null); window.location.reload(); }}
                className="px-5 py-2.5 bg-[#1e3a8a] text-white font-semibold rounded-lg hover:bg-[#172554] transition text-sm"
              >
                Try Again
              </button>
            </div>
          </div>
        </div>
      );
    }
    return (
      <div className="w-full bg-white min-h-screen flex flex-col items-center justify-center gap-4">
        <div className="w-12 h-12 border-4 border-[#1e3a8a] border-t-transparent rounded-full animate-spin" />
        <p className="text-slate-600 font-semibold text-lg">Preparing your test...</p>
        <p className="text-slate-400 text-sm">Generating questions from the bank</p>
      </div>
    );
  }

  // ── Results Summary ───────────────────────────────────────────────────────
  if (phase === 'results_summary') {
    // Drive the list from SECTION_PROGRESSION — the authoritative set of sections
    // for this test — instead of from whatever happened to get recorded. A
    // 4-section test therefore ALWAYS renders 4 rows, in order, even if a section
    // was skipped or its result failed to record. Previously the page rendered
    // sectionResults directly, so a missing entry silently dropped a whole row and
    // a duplicate entry added a spurious one.
    const summaryRows = SECTION_PROGRESSION.map((s, i) => {
      const recorded = sectionResults.find(r => r.index === i);
      const name = s.name.charAt(0).toUpperCase() + s.name.slice(1);
      return {
        index: i,
        name: recorded?.name ?? name,
        answered: recorded?.answered ?? 0,
        total: recorded?.total ?? 0,
        attempted: !!recorded && recorded.total > 0,
      };
    });

    const totalQuestions = summaryRows.reduce((sum, r) => sum + r.total, 0);
    const totalAnswered = summaryRows.reduce((sum, r) => sum + r.answered, 0);
    const percentage = totalQuestions > 0 ? Math.round((totalAnswered / totalQuestions) * 100) : 0;
    const allComplete = summaryRows.every(r => r.attempted && r.answered === r.total);

    // Why a section is not at 100%. Reading the code cannot distinguish "the
    // section timed out with answers missing" from "the section was never
    // recorded", and both render as a non-100% row — so state it on screen and in
    // the console. A bug report or screenshot then carries its own diagnosis.
    const shortfallReason = (row: typeof summaryRows[number]): string => {
      if (!row.attempted) return 'no result was recorded for this section';
      if (row.answered < row.total) return `${row.total - row.answered} question(s) left unanswered when the section ended`;
      return '';
    };
    if (!allComplete) {
      console.warn('[review-submit] sections not at 100%', {
        recorded: sectionResults,
        rendered: summaryRows,
        sectionCount: SECTION_PROGRESSION.length,
      });
    }

    const now    = new Date();
    const dayStr = now.toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' }).toUpperCase();
    const timeStr = now.toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit', hour12: false });

    return (
      <div className="min-h-screen" style={{ background: '#F8F9FB' }}>
        <div className="max-w-5xl mx-auto px-6 md:px-10 pt-10 pb-16">

          {/* Breadcrumb — same shape as section intro */}
          <div className="mb-6 text-sm flex items-center gap-2">
            <span style={{ color: '#64748B' }}>Mock Tests</span>
            <span style={{ color: '#CBD5E1' }}>›</span>
            <span style={{ color: '#64748B' }}>{testName}</span>
            <span style={{ color: '#CBD5E1' }}>›</span>
            <span className="font-semibold" style={{ color: '#0F172A' }}>Review &amp; Submit</span>
          </div>

          {/* Main card */}
          <div
            className="bg-white rounded-2xl border p-8 md:p-10"
            style={{
              borderColor: '#E5E7EB',
              boxShadow: '0 1px 2px rgba(15,23,42,0.04), 0 8px 24px -12px rgba(15,23,42,0.06)',
            }}
          >
            {/* Header */}
            <div className="flex items-start justify-between gap-4 mb-7 flex-wrap">
              <div>
                {/* Badge and copy now follow the actual data. They previously
                    asserted "Test Complete / All N sections attempted"
                    unconditionally, even when a section was partial or missing. */}
                <span
                  className="inline-flex items-center gap-1.5 px-2.5 py-1 rounded-full text-[11px] font-bold tracking-wider uppercase mb-3"
                  style={allComplete
                    ? { background: '#dcfce7', color: '#15803d', border: '1px solid #bbf7d0' }
                    : { background: '#fef3c7', color: '#92400e', border: '1px solid #fde68a' }}
                >
                  {allComplete
                    ? <><CheckCircle size={11} /> Test Complete</>
                    : <><AlertTriangle size={11} /> Incomplete</>}
                </span>
                <h2 className="text-2xl font-bold tracking-tight" style={{ color: '#0F172A', letterSpacing: '-0.02em' }}>
                  Review your attempt
                </h2>
                <p className="text-sm mt-1.5" style={{ color: '#64748B' }}>
                  {allComplete
                    ? `All ${SECTION_PROGRESSION.length} sections completed. Submit to receive your full score report.`
                    : `${summaryRows.filter(r => r.attempted && r.answered === r.total).length} of ${SECTION_PROGRESSION.length} sections fully answered. You can still submit — unanswered questions score zero.`}
                </p>
              </div>
              <div className="text-right shrink-0">
                <p className="text-[10px] font-bold tracking-widest uppercase" style={{ color: '#94A3B8' }}>Submitted</p>
                <p className="text-xs font-semibold mt-0.5" style={{ color: '#475569' }}>{dayStr} · {timeStr}</p>
              </div>
            </div>

            {/* Numbered section list — same shape as section intro instructions */}
            <ol className="space-y-4 mb-7">
              {summaryRows.map((result, i) => {
                // `done` now requires total > 0. It used to be a bare
                // `answered === total`, which is TRUE for 0 === 0 — so a section
                // with no recorded questions rendered a green "complete" tick
                // next to 0%, contradicting itself.
                const pct  = result.total > 0 ? Math.round((result.answered / result.total) * 100) : 0;
                const done = result.attempted && result.answered === result.total;
                return (
                  <li key={result.index} className="flex gap-3 text-[15px] leading-relaxed">
                    <span className="font-semibold tabular-nums shrink-0 w-5" style={{ color: '#475569' }}>{i + 1}.</span>
                    <div className="flex-1 min-w-0">
                      <div className="flex items-center justify-between gap-3 flex-wrap">
                        <div>
                          <span className="font-bold" style={{ color: '#000' }}>{result.name}:</span>{' '}
                          <span style={{ color: '#2d2d2d' }}>
                            {result.attempted ? `${result.answered} of ${result.total} answered` : 'not attempted'}
                          </span>
                          {/* Spell out the shortfall rather than leaving the user to
                              infer it from a percentage. */}
                          {!done && (
                            <span className="block text-xs mt-0.5" style={{ color: '#b45309' }}>
                              {shortfallReason(result)}
                            </span>
                          )}
                        </div>
                        <div className="flex items-center gap-3 shrink-0">
                          <div className="w-32" aria-hidden>
                            <div className="w-full rounded-full overflow-hidden" style={{ height: 5, background: '#f1f5f9' }}>
                              <div
                                className="h-full rounded-full transition-all"
                                style={{ width: `${pct}%`, background: done ? '#22c55e' : '#1e3a8a' }}
                              />
                            </div>
                          </div>
                          <span className="text-xs font-bold tabular-nums w-10 text-right" style={{ color: done ? '#15803d' : '#1e3a8a' }}>{pct}%</span>
                          {done
                            ? <CheckCircle size={16} style={{ color: '#22c55e' }} />
                            : <span className="text-[10px] font-bold px-2 py-0.5 rounded uppercase tracking-wider" style={{ background: '#fef3c7', color: '#92400e' }}>
                                {result.attempted ? 'Partial' : 'Skipped'}
                              </span>
                          }
                        </div>
                      </div>
                    </div>
                  </li>
                );
              })}
            </ol>

            {/* Summary highlight box — mirrors the section intro "1 Score = 1 Point" box */}
            <div
              className="rounded-xl px-5 py-4 flex items-center justify-between gap-4 flex-wrap"
              style={{ background: '#EFF6FF', border: '1px solid #BFDBFE' }}
            >
              <p className="text-sm leading-relaxed" style={{ color: '#2d2d2d' }}>
                Once submitted, your answers cannot be changed.<br />
                Results will be available immediately after submission.
              </p>
              <div className="flex items-center gap-4 shrink-0">
                <div className="text-right">
                  <p className="text-[10px] font-bold tracking-widest uppercase" style={{ color: '#94A3B8' }}>Answered</p>
                  <p className="text-2xl font-bold tabular-nums" style={{ color: '#1E3A8A' }}>{totalAnswered}<span className="text-base font-bold" style={{ color: '#60A5FA' }}>/{totalQuestions}</span></p>
                </div>
                <div className="text-right">
                  <p className="text-[10px] font-bold tracking-widest uppercase" style={{ color: '#94A3B8' }}>Completion</p>
                  <p className="text-2xl font-bold tabular-nums" style={{ color: percentage === 100 ? '#15803d' : '#b45309' }}>{percentage}%</p>
                </div>
              </div>
            </div>
          </div>

          {/* Completed pills — driven by the same summaryRows as the list above so
              the two can never disagree about a section's status. */}
          <div className="flex flex-wrap gap-2 mt-5">
            {summaryRows.map(r => {
              const done = r.attempted && r.answered === r.total;
              return (
                <div
                  key={r.index}
                  className="flex items-center gap-1.5 px-3 py-1.5 rounded-full text-xs font-bold"
                  style={done
                    ? { background: '#ECFDF5', color: '#059669', border: '1px solid #A7F3D0' }
                    : { background: '#FFFBEB', color: '#B45309', border: '1px solid #FDE68A' }}
                >
                  {/* Green check only when fully answered; a partial section (e.g. timer
                      expired at 8/10) shows an amber pill, never a completed tick. */}
                  {done
                    ? <><CheckCircle size={11} /> {r.name}: {r.answered}/{r.total}</>
                    : <><AlertTriangle size={11} /> {r.name}: {r.attempted ? `${r.answered}/${r.total} partial` : 'skipped'}</>}
                </div>
              );
            })}
          </div>

          {/* Submission failure. Kept on screen (not just a toast) so the user
              can see the report was NOT submitted and act on it. */}
          {finalSubmitError && (
            <div
              className="mt-5 rounded-xl px-5 py-4 flex items-start gap-3"
              style={{ background: '#fef2f2', border: '1px solid #fecaca' }}
              role="alert"
            >
              <AlertTriangle size={18} style={{ color: '#dc2626' }} className="shrink-0 mt-0.5" />
              <div className="flex-1 min-w-0">
                <p className="text-sm font-bold mb-0.5" style={{ color: '#991b1b' }}>
                  Your test was not submitted
                </p>
                <p className="text-sm leading-relaxed" style={{ color: '#7f1d1d' }}>
                  {finalSubmitError} Your answers are saved — press Retry Submit to try again.
                </p>
              </div>
            </div>
          )}

          {/* Bottom action row — same shape as section intro */}
          <div className="mt-6 flex items-center justify-between flex-wrap gap-3">
            <button
              onClick={() => router.push('/mock-test')}
              className="text-sm font-medium hover:underline"
              style={{ color: '#475569' }}
            >
              ← Back to Tests
            </button>

            <button
              onClick={finalSubmit}
              className="flex items-center gap-2 px-6 py-3 rounded-xl text-sm font-bold text-white transition hover:-translate-y-0.5 hover:shadow-[0_8px_24px_-6px_rgba(30,58,138,0.5)]"
              style={{ background: '#1e3a8a', boxShadow: '0 4px 14px -4px rgba(30,58,138,0.35)' }}
            >
              <CheckCircle size={16} />
              {finalSubmitError ? 'Retry Submit' : 'Submit Full Test'}
            </button>
          </div>
        </div>
      </div>
    );
  }

  // ── Submitting ─────────────────────────────────────────────────────────────
  if (phase === 'submitting') {
    return (
      <div className="w-full min-h-screen flex flex-col items-center justify-center gap-5" style={{ background: '#ffffff' }}>
        <div className="w-12 h-12 border-4 rounded-full animate-spin" style={{ borderColor: '#dbeafe', borderTopColor: '#1e3a8a' }} />
        <p className="font-bold text-xs tracking-widest uppercase" style={{ color: '#1e3a8a' }}>Scoring your test</p>
        <p className="text-sm" style={{ color: '#9ca3af' }}>Please wait while we calculate your results</p>
      </div>
    );
  }

  // ── Loading Next Section (removed - sections load in background) ───────────

  // ── Section Intro ──────────────────────────────────────────────────────────
  if (phase === 'section_intro') {
    const sName     = currentSection?.section_name ?? 'Section';
    const qCount    = currentSection?.question_count ?? 10;
    const dur       = currentSection?.duration_minutes ?? 20;
    const passCount = Math.ceil(qCount * 0.6);
    const passPct   = Math.round((passCount / qCount) * 100);

    return (
      <div className="min-h-screen" style={{ background: '#F8F9FB' }}>
        <div className="max-w-5xl mx-auto px-6 md:px-10 pt-10 pb-16">

          {/* Breadcrumb */}
          <div className="mb-6 text-sm flex items-center gap-2">
            <span style={{ color: '#64748B' }}>Mock Tests</span>
            <span style={{ color: '#CBD5E1' }}>›</span>
            <span className="font-semibold" style={{ color: '#0F172A' }}>{testName} — {sName}</span>
          </div>

          {/* Instructions card */}
          <div
            className="bg-white rounded-2xl border p-8 md:p-10"
            style={{
              borderColor: '#E5E7EB',
              boxShadow: '0 1px 2px rgba(15,23,42,0.04), 0 8px 24px -12px rgba(15,23,42,0.06)',
            }}
          >
            <h2 className="text-xl font-bold mb-7" style={{ color: '#0F172A' }}>Instructions:</h2>

            <ol className="space-y-5 mb-7">
              {[
                { label: 'Number of Questions', value: String(qCount) },
                { label: 'Type of Questions',   value: 'Multiple Choice (MCQ) · 4 options each' },
                { label: 'Duration',            value: `${dur} mins` },
                {
                  label: 'Marking Scheme',
                  value: hasNegMarking
                    ? '1 mark for each correct answer · 1/3 mark deducted for each wrong answer'
                    : '1 mark for each correct answer · No negative marking',
                },
                { label: 'Attempts',     value: 'Each section can be attempted once in this session' },
                { label: 'Cutoff Marks', value: `You need to score a minimum of ${passCount} marks (${passPct}%) to pass` },
              ].map((item, i) => (
                <li key={i} className="flex gap-3 text-[15px] leading-relaxed">
                  <span className="font-semibold tabular-nums shrink-0 w-5" style={{ color: '#475569' }}>{i + 1}.</span>
                  <div style={{ color: '#2d2d2d' }}>
                    <span className="font-bold" style={{ color: '#000' }}>{item.label}:</span> {item.value}
                  </div>
                </li>
              ))}
            </ol>

            {/* Highlight box — points/score */}
            <div
              className="rounded-xl px-5 py-4 flex items-center justify-between gap-4 flex-wrap"
              style={{ background: '#EFF6FF', border: '1px solid #BFDBFE' }}
            >
              <p className="text-sm leading-relaxed" style={{ color: '#2d2d2d' }}>
                Points will be awarded based on your<br />score in MCQ questions
              </p>
              <div className="flex items-center gap-2 font-bold shrink-0" style={{ color: '#0F172A' }}>
                <span>1 Score</span>
                <span>=</span>
                <span className="w-7 h-7 rounded-full flex items-center justify-center" style={{ background: '#1E3A8A' }}>
                  <Star size={14} fill="#fff" stroke="#fff" />
                </span>
                <span>1 Point</span>
              </div>
            </div>
          </div>

          {/* Proctoring consent. Shown BEFORE the camera prompt so the browser's
              permission dialog is expected rather than a surprise, and so the
              user knows what is recorded and why before they commit. */}
          {!recorder.isRecording && (
            <div
              className="mt-5 rounded-xl px-5 py-4 flex items-start gap-3"
              style={{ background: '#EFF6FF', border: '1px solid #BFDBFE' }}
            >
              <EyeOff size={18} style={{ color: '#1e3a8a' }} className="shrink-0 mt-0.5" />
              <div className="flex-1 min-w-0">
                <p className="text-sm font-bold mb-0.5" style={{ color: '#0F172A' }}>
                  This test is proctored
                </p>
                <p className="text-sm leading-relaxed" style={{ color: '#2d2d2d' }}>
                  Your camera and microphone are recorded for the duration of the test and the
                  recording is submitted for automated review. Your browser will ask for
                  permission when you start — the test cannot begin without it.
                </p>
              </div>
            </div>
          )}

          {/* Why the section could not start. Stays on screen until the next
              attempt — an out-of-credits 402 needs an action, not a toast. */}
          {sectionError && (
            <div
              className="mt-5 rounded-xl px-5 py-4 flex items-start gap-3 flex-wrap"
              style={{ background: '#fef2f2', border: '1px solid #fecaca' }}
              role="alert"
            >
              <AlertTriangle size={18} style={{ color: '#dc2626' }} className="shrink-0 mt-0.5" />
              <div className="flex-1 min-w-0">
                <p className="text-sm font-bold mb-0.5" style={{ color: '#991b1b' }}>
                  {sectionError.insufficientCredits ? 'Not enough credits' : `Couldn't start ${sName}`}
                </p>
                <p className="text-sm leading-relaxed" style={{ color: '#7f1d1d' }}>
                  {sectionError.message}
                </p>
              </div>
              {sectionError.insufficientCredits && (
                <button
                  onClick={() => router.push('/settings/subscription')}
                  className="px-4 py-2 rounded-lg text-xs font-bold text-white transition hover:opacity-90 shrink-0"
                  style={{ background: '#dc2626' }}
                >
                  Get credits
                </button>
              )}
            </div>
          )}

          {/* Previously completed pills */}
          {sectionResults.length > 0 && (
            <div className="flex flex-wrap gap-2 mt-5">
              {sectionResults.map(r => {
                // total > 0 guard: `answered === total` alone is true for 0 === 0,
                // so an empty section rendered a green "complete" tick.
                const done = r.total > 0 && r.answered === r.total;
                return (
                  <div
                    key={r.index}
                    className="flex items-center gap-1.5 px-3 py-1.5 rounded-full text-xs font-bold"
                    style={done
                      ? { background: '#ECFDF5', color: '#059669', border: '1px solid #A7F3D0' }
                      : { background: '#FFFBEB', color: '#B45309', border: '1px solid #FDE68A' }}
                  >
                    {/* Green check only when fully answered; a partial section (e.g. timer
                        expired at 8/10) shows an amber "partial" pill, never a completed tick. */}
                    {done
                      ? <><CheckCircle size={11} /> {r.name}: {r.answered}/{r.total}</>
                      : <><AlertTriangle size={11} /> {r.name}: {r.answered}/{r.total} partial</>}
                  </div>
                );
              })}
            </div>
          )}

          {/* Bottom action row */}
          <div className="mt-6 flex items-center justify-between flex-wrap gap-3">
            <button
              onClick={() => router.push('/mock-test')}
              className="text-sm font-medium hover:underline"
              style={{ color: '#475569' }}
            >
              ← Back
            </button>

            <div className="flex items-center gap-3">
              {sectionResults.length > 0 && (
                <button
                  onClick={() => setPhase('results_summary')}
                  className="text-sm font-medium px-4 py-2.5 rounded-xl border bg-white"
                  style={{ borderColor: '#E5E7EB', color: '#2d2d2d' }}
                >
                  Skip &amp; View Results
                </button>
              )}
              <button
                onClick={handleStartSection}
                disabled={loadingSection}
                className="flex items-center gap-2 px-6 py-3 rounded-xl text-sm font-bold text-white transition hover:-translate-y-0.5 hover:shadow-[0_8px_24px_-6px_rgba(30,58,138,0.5)] disabled:opacity-60 disabled:hover:translate-y-0"
                style={{ background: '#1e3a8a', boxShadow: '0 4px 14px -4px rgba(30,58,138,0.35)' }}
              >
                {loadingSection ? (
                  <>
                    <div className="w-4 h-4 border-2 border-white border-t-transparent rounded-full animate-spin" />
                    Starting…
                  </>
                ) : (
                  <>
                    Start {sName}
                    <ChevronRight size={16} />
                  </>
                )}
              </button>
            </div>
          </div>
        </div>
      </div>
    );
  }

  // ── Section Testing ────────────────────────────────────────────────────────
  const isTimerWarning  = timeRemaining > 0 && timeRemaining <= 300;
  const isTimerCritical = timeRemaining > 0 && timeRemaining <= 60;

  // On the final question the Submit action moves from the header down into the
  // Next slot, so exactly one Submit button is on screen at any time.
  const isOnLastQuestion = questions.length > 0 && currentQ === questions.length - 1;

  // Single source of truth for palette swatch styling. The desktop rail and the
  // mobile strip both read this so the two can never drift out of sync.
  const paletteStyle = (i: number): React.CSSProperties => {
    const q         = questions[i];
    const isAns     = q?.selected !== null && q?.selected !== undefined;
    const isFlagged = !!q?.markedForReview;
    const isCurrent = i === currentQ;
    return {
      background: isCurrent ? '#1e3a8a' : isFlagged ? '#fef3c7' : isAns ? '#dbeafe' : '#f9fafb',
      color:      isCurrent ? '#ffffff' : isFlagged ? '#92400e' : isAns ? '#1e3a8a' : '#9ca3af',
      border:     isCurrent ? '2px solid #1e3a8a' : isFlagged ? '1px solid #fde68a' : isAns ? '1px solid #bfdbfe' : '1px solid #f3f4f6',
      boxShadow:  isCurrent ? '0 0 0 3px #dbeafe' : 'none',
    };
  };

  const paletteLabel = (i: number): string => {
    const q = questions[i];
    const state = q?.markedForReview ? 'marked for review'
      : q?.selected != null ? 'answered'
      : 'not answered';
    return `Question ${i + 1}, ${state}`;
  };

  // The answer feedback body is rendered in two places — the desktop side rail
  // and, below lg where that rail is hidden, inline under the question. Building
  // it once keeps them identical.
  const feedbackBody = answerFeedback ? (
    <div className="flex-1 flex flex-col">
      <div
        className="flex items-center gap-2 px-4 py-3"
        style={{ background: answerFeedback.is_correct ? '#dcfce7' : '#fee2e2', borderBottom: `1px solid ${answerFeedback.is_correct ? '#bbf7d0' : '#fecaca'}` }}
      >
        {answerFeedback.is_correct
          ? <CheckCircle size={15} style={{ color: '#15803d' }} />
          : <span className="font-bold text-base leading-none" style={{ color: '#991b1b' }}>✗</span>
        }
        <span className="font-bold text-xs tracking-widest" style={{ color: answerFeedback.is_correct ? '#15803d' : '#991b1b' }}>
          {answerFeedback.is_correct ? 'CORRECT' : 'INCORRECT'}
        </span>
        {!answerFeedback.is_correct && answerFeedback.correct_answer && (
          <span className="ml-auto text-xs font-semibold" style={{ color: '#7f1d1d' }}>{answerFeedback.correct_answer}</span>
        )}
      </div>

      <div className="p-4 space-y-4 flex-1">
        {answerFeedback.solution_steps && answerFeedback.solution_steps.length > 0 && (
          <div>
            <p className="text-[10px] font-bold tracking-widest mb-2" style={{ color: '#9ca3af' }}>SOLUTION PATH</p>
            <ol className="space-y-2">
              {answerFeedback.solution_steps.map((step, i) => (
                <li key={i} className="flex items-start gap-2 text-xs" style={{ color: '#1f2937' }}>
                  <span
                    className="w-4 h-4 rounded flex items-center justify-center text-[10px] font-bold shrink-0 mt-0.5"
                    style={{ background: '#dbeafe', color: '#1e3a8a' }}
                  >{i + 1}</span>
                  {step}
                </li>
              ))}
            </ol>
          </div>
        )}
        {answerFeedback.explanation && (
          <div>
            <p className="text-[10px] font-bold tracking-widest mb-1" style={{ color: '#9ca3af' }}>EXPLANATION</p>
            <p className="text-xs leading-relaxed whitespace-pre-line" style={{ color: '#1f2937' }}>
              {answerFeedback.explanation}
            </p>
          </div>
        )}
        {answerFeedback.feedback && (
          <div className="p-3 rounded-xl" style={{ background: '#eff6ff', border: '1px solid #dbeafe' }}>
            <p className="text-[10px] font-bold tracking-widest mb-1" style={{ color: '#1e3a8a' }}>AI PATTERN</p>
            <p className="text-xs leading-relaxed" style={{ color: '#1f2937' }}>{answerFeedback.feedback}</p>
          </div>
        )}
      </div>
    </div>
  ) : null;

  return (
    <div className="w-full min-h-screen flex flex-col" style={{ background: '#F8F9FB' }}>
      {/* Lockdown violation modal — blocks the UI until the user returns to fullscreen */}
      <AnimatePresence>
        {showTabWarning && phase === 'section_testing' && (
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            className="fixed inset-0 z-100 flex items-center justify-center p-6"
            style={{ background: 'rgba(0,0,0,0.85)', backdropFilter: 'blur(4px)' }}
          >
            <div className="bg-white rounded-2xl p-8 max-w-md w-full text-center shadow-2xl" role="dialog" aria-modal="true" aria-labelledby="focus-lost-title">
              <div className="mx-auto mb-4 w-14 h-14 rounded-full flex items-center justify-center" style={{ background: '#fee2e2' }}>
                <AlertTriangle size={28} style={{ color: '#dc2626' }} />
              </div>
              <h2 id="focus-lost-title" className="text-xl font-bold mb-2" style={{ color: '#000' }}>Focus lost</h2>
              <p className="text-sm mb-1" style={{ color: '#2d2d2d' }}>
                Switching tabs, leaving fullscreen, or switching applications during the exam is not allowed.
              </p>
              <p className="text-xs font-bold mb-6" style={{ color: '#dc2626' }}>
                Violation #{tabSwitchCount} — this has been recorded.
              </p>
              <button
                onClick={() => {
                  setShowTabWarning(false);
                  if (typeof document !== 'undefined' && !document.fullscreenElement) {
                    document.documentElement.requestFullscreen().catch(() => {});
                  }
                }}
                className="w-full py-3 rounded-xl text-white font-bold text-sm tracking-wide hover:opacity-90 transition"
                style={{ background: '#1e3a8a' }}
              >
                Resume in Fullscreen
              </button>
            </div>
          </motion.div>
        )}
      </AnimatePresence>

      {/* Exit confirmation modal */}
      <AnimatePresence>
        {showExitConfirm && (
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            className="fixed inset-0 z-100 flex items-center justify-center p-6"
            style={{ background: 'rgba(0,0,0,0.7)', backdropFilter: 'blur(4px)' }}
          >
            <div className="bg-white rounded-2xl p-7 max-w-md w-full shadow-2xl" role="dialog" aria-modal="true" aria-labelledby="exit-confirm-title">
              <div className="flex items-start gap-3 mb-4">
                <div className="w-10 h-10 rounded-full flex items-center justify-center shrink-0" style={{ background: '#fef3c7' }}>
                  <AlertTriangle size={20} style={{ color: '#d97706' }} />
                </div>
                <div className="flex-1">
                  <h2 id="exit-confirm-title" className="text-lg font-bold mb-1" style={{ color: '#000' }}>Exit the test?</h2>
                  <p className="text-sm" style={{ color: '#2d2d2d' }}>
                    Your progress in this section will be lost and the session will be closed.
                    You can start a new test from the dashboard anytime.
                  </p>
                </div>
              </div>
              <div className="flex gap-2 mt-5">
                <button
                  onClick={() => setShowExitConfirm(false)}
                  disabled={exitSubmitting}
                  className="flex-1 py-2.5 rounded-lg border text-sm font-bold hover:bg-slate-50 transition disabled:opacity-60"
                  style={{ borderColor: '#d1d5db', color: '#2d2d2d' }}
                >
                  STAY IN TEST
                </button>
                <button
                  onClick={handleExitTest}
                  disabled={exitSubmitting}
                  className="flex-1 py-2.5 rounded-lg text-white text-sm font-bold transition disabled:opacity-60 hover:opacity-90"
                  style={{ background: '#dc2626' }}
                >
                  {exitSubmitting ? 'EXITING...' : 'EXIT & GO TO DASHBOARD'}
                </button>
              </div>
            </div>
          </motion.div>
        )}
      </AnimatePresence>

      {/* NXT Wave-style practice header */}
      <div className="bg-white shrink-0">
        {/* One row, one vertical centre line. The previous header mixed
            items-stretch / justify-center / items-end across three columns, so
            nothing shared a baseline — that was the "ragged" look. */}
        <div className="flex items-center justify-between gap-3 md:gap-6 px-4 md:px-8 py-3">
          {/* Left: section identity. No longer a button — a back-chevron that
              silently abandoned the test was a trap; ending is an explicit
              action on the right. */}
          <div className="flex flex-col gap-0.5 min-w-0">
            <span className="text-sm font-bold tracking-wide truncate" style={{ color: '#1f2937' }}>
              {currentSection?.section_name}
            </span>
            <span className="text-[11px] font-bold tracking-wider uppercase" style={{ color: '#6b7280' }}>
              Section {currentSectionProgressionIndex + 1} of {SECTION_PROGRESSION.length}
            </span>
          </div>

          {/* Right: timer, progress, actions. The attempted count lives here ONLY —
              it used to be repeated in a centre badge and again in the footer. */}
          <div className="flex items-center gap-2 md:gap-3 shrink-0">
            {/* Recording indicator — the user must be able to see, at any moment,
                that they are being recorded. */}
            {recorder.isRecording && (
              <span
                className="flex items-center gap-1.5 px-2 py-1.5 rounded-md text-[10px] font-bold tracking-wider uppercase"
                style={{ background: '#fee2e2', color: '#991b1b', border: '1px solid #fecaca' }}
                title="This test is proctored — your camera is recording"
              >
                <span className="w-1.5 h-1.5 rounded-full animate-pulse" style={{ background: '#dc2626' }} aria-hidden="true" />
                <span className="hidden sm:inline">Rec</span>
              </span>
            )}
            <div className="hidden sm:flex flex-col items-end leading-tight">
              <span className="text-sm font-bold tabular-nums" style={{ color: '#1e3a8a' }}>
                {answered}/{questions.length}
              </span>
              <span className="text-[10px] font-bold tracking-wider uppercase" style={{ color: '#6b7280' }}>
                Attempted
              </span>
            </div>

            <div
              className={`flex items-center px-2.5 py-1.5 rounded-md text-xs font-bold tabular-nums ${isTimerCritical ? 'animate-pulse' : ''}`}
              style={{
                background: isTimerCritical ? '#fee2e2' : isTimerWarning ? '#fef3c7' : '#eff6ff',
                color: isTimerCritical ? '#991b1b' : isTimerWarning ? '#92400e' : '#1e3a8a',
                border: `1px solid ${isTimerCritical ? '#fecaca' : isTimerWarning ? '#fde68a' : '#bfdbfe'}`,
              }}
            >
              <span className="font-mono">{formatTime(timeRemaining)}</span>
            </div>

            {/* Exit. Always visible at every breakpoint — this is the only way out
                of a fullscreen, locked-down test, so it must be unmistakable.
                A bare "End" label read as a minor secondary action and was reported
                as the exit button being missing; it now carries an icon, the word
                "Exit", and a danger tint so it is recognisable at a glance. */}
            <button
              onClick={() => setShowExitConfirm(true)}
              disabled={sectionSubmitting || exitSubmitting}
              className="flex items-center gap-1.5 text-[11px] font-bold tracking-wider uppercase px-3 py-2 rounded-md border transition hover:bg-red-50 disabled:opacity-40 whitespace-nowrap"
              style={{ color: '#b91c1c', borderColor: '#fecaca', background: '#fff' }}
              title="Exit the test and return to your dashboard"
              aria-label="Exit test"
            >
              <LogOut size={13} aria-hidden="true" />
              Exit
            </button>
            {/* Hidden on the last question, where the Submit action moves down into
                the Next slot beside the question. Keeping both visible is what put
                two identical Submit buttons on screen at once. */}
            <button
              onClick={handleSectionSubmit}
              disabled={sectionSubmitting}
              className={`text-[11px] font-bold tracking-wider uppercase px-3 py-2 rounded-md text-white transition disabled:opacity-60 hover:opacity-90 whitespace-nowrap ${
                isOnLastQuestion ? 'hidden' : ''
              }`}
              style={{ background: isLastSection ? '#059669' : '#1e3a8a' }}
              title="Keyboard shortcut: press S"
              aria-keyshortcuts="s"
            >
              {/* Same wording as the in-flow submit at the end of the question list —
                  one action should not have two names. Shortened on narrow screens
                  only, where the full label would push the header into a wrap. */}
              {sectionSubmitting ? '…' : (
                <>
                  Submit
                  <span className="hidden sm:inline">{isLastSection ? ' Test' : ' Section'}</span>
                </>
              )}
              <kbd className="hidden md:inline-block ml-1.5 px-1 rounded text-[9px] font-bold align-middle" style={{ background: 'rgba(255,255,255,0.2)', color: '#fff' }}>S</kbd>
            </button>
          </div>
        </div>

        {/* Mobile question palette. Below md the side rail is hidden, which
            previously left phones with NO way to jump between questions. */}
        <div className="md:hidden flex gap-1.5 px-4 pb-3 overflow-x-auto" role="group" aria-label="Question navigation">
          {questions.map((_, i) => (
            <button
              key={i}
              onClick={() => setCurrentQ(i)}
              aria-label={paletteLabel(i)}
              aria-current={i === currentQ ? 'true' : undefined}
              className="w-11 h-11 rounded-lg text-xs font-bold flex items-center justify-center transition shrink-0"
              style={paletteStyle(i)}
            >
              {i + 1}
            </button>
          ))}
        </div>

        {/* Thin purple progress bar */}
        <div className="h-1" style={{ background: '#f1f5f9' }}>
          <motion.div
            className="h-full"
            initial={{ width: 0 }}
            animate={{ width: `${((currentQ + 1) / Math.max(questions.length, 1)) * 100}%` }}
            transition={{ duration: 0.3 }}
            style={{ background: '#1e3a8a' }}
          />
        </div>
      </div>

      {/* Three-column body */}
      <div className="flex flex-1 overflow-hidden">

        {/* Left: question palette rail (desktop). A two-up auto-fill grid so a
            30+ question section stays usable instead of running off the bottom
            of a single fixed column. */}
        <nav
          className="hidden md:grid content-start w-16 lg:w-20 shrink-0 p-3 gap-2 overflow-y-auto border-r"
          style={{
            background: '#ffffff',
            borderColor: '#f3f4f6',
            gridTemplateColumns: 'repeat(auto-fill, minmax(36px, 1fr))',
          }}
          aria-label="Question navigation"
        >
          {questions.map((_, i) => (
            <button
              key={i}
              onClick={() => setCurrentQ(i)}
              aria-label={paletteLabel(i)}
              aria-current={i === currentQ ? 'true' : undefined}
              className="aspect-square min-h-[36px] rounded-lg text-xs font-bold flex items-center justify-center transition"
              style={paletteStyle(i)}
            >
              {i + 1}
            </button>
          ))}
        </nav>

        {/* Center: question area — NXT Wave style (centered, minimal) */}
        <motion.div
          key={currentQ}
          initial={{ opacity: 0, x: 10 }}
          animate={{ opacity: 1, x: 0 }}
          className="flex-1 overflow-y-auto"
          style={{ background: '#ffffff' }}
        >
          <div className="max-w-3xl mx-auto px-4 sm:px-6 md:px-8 pt-5 md:pt-8 pb-6 flex flex-col min-h-full">
            {/* Tiny meta row */}
            <div className="flex items-center gap-2 mb-6 text-[11px] font-bold tracking-widest" style={{ color: '#9ca3af' }}>
              <span>QUESTION {String(currentQ + 1).padStart(2, '0')}/{String(questions.length).padStart(2, '0')}</span>
              {/* Flags the end of the section the moment the candidate lands on it,
                  rather than leaving them to work it out from the counter. */}
              {isOnLastQuestion && (
                <span className="px-2 py-0.5 rounded uppercase" style={{ background: '#fef3c7', color: '#92400e' }}>
                  Last question
                </span>
              )}
              {hasNegMarking && (
                <span className="px-2 py-0.5 rounded uppercase" style={{ background: '#fee2e2', color: '#991b1b' }}>
                  Neg Mark
                </span>
              )}
              {currentQuestion?.markedForReview && (
                <span className="px-2 py-0.5 rounded uppercase" style={{ background: '#fef3c7', color: '#92400e' }}>
                  ⭐ Marked
                </span>
              )}
              {tabSwitchCount > 0 && (
                <span className="ml-auto flex items-center gap-1" style={{ color: '#ef4444' }}>
                  <EyeOff size={10} /> {tabSwitchCount} switch
                </span>
              )}
            </div>

            {/* Question text */}
            <div className="pb-5 mb-5 border-b" style={{ borderColor: '#e5e7eb', userSelect: 'none' }}>
              <p className="text-base font-semibold leading-relaxed" style={{ color: '#111827' }}>
                {currentQuestion?.text}
              </p>
            </div>

            {/* Options (radio circle + text) */}
            <div className="space-y-3 mb-10">
              {currentQuestion?.options.map((option, idx) => {
                const isSelected    = currentQuestion.selected === option;
                const correctLetter = answerFeedback?.correct_answer?.trim().charAt(0).toUpperCase();
                const correctIndex  = correctLetter ? correctLetter.charCodeAt(0) - 65 : -1;
                const isCorrect     = answerFeedback !== null && correctIndex === idx;
                const isWrong       = answerFeedback !== null && isSelected && !answerFeedback.is_correct;

                let textColor = '#1f2937';
                let dotBorder = '#d1d5db';
                let dotFill   = 'transparent';
                if (answerFeedback) {
                  if (isCorrect)    { textColor = '#15803d'; dotBorder = '#22c55e'; dotFill = '#22c55e'; }
                  else if (isWrong) { textColor = '#991b1b'; dotBorder = '#ef4444'; dotFill = '#ef4444'; }
                  else if (isSelected) { dotBorder = '#1e3a8a'; dotFill = '#1e3a8a'; }
                } else if (isSelected) {
                  dotBorder = '#1e3a8a'; dotFill = '#1e3a8a';
                }

                const isLocked = !!currentQuestion?.locked;
                const letter = String.fromCharCode(65 + idx);
                return (
                  <label
                    key={idx}
                    aria-label={`Option ${letter}: ${option}`}
                    // min-h-[52px] + horizontal padding: the row was py-2.5 only,
                    // which fell under the 44px minimum tap target on phones.
                    className={`flex items-center gap-3.5 min-h-[52px] px-3 -mx-3 py-2.5 rounded-lg transition ${answerSubmitting || isLocked ? 'cursor-not-allowed' : 'cursor-pointer hover:bg-slate-50'}${answerSubmitting ? ' opacity-70' : ''}`}
                  >
                    <span
                      className="w-5 h-5 rounded-full border-2 flex items-center justify-center shrink-0 transition"
                      style={{ borderColor: dotBorder, background: 'transparent' }}
                      aria-hidden="true"
                    >
                      {(isSelected || isCorrect) && (
                        <span className="w-2.5 h-2.5 rounded-full" style={{ background: dotFill }} />
                      )}
                    </span>
                    <input
                      type="radio"
                      name="answer"
                      value={option}
                      checked={isSelected}
                      onChange={() => handleSelectAnswer(option)}
                      disabled={answerSubmitting || isLocked}
                      aria-label={`Option ${letter}: ${option}`}
                      className="sr-only"
                    />
                    <span className="flex-1 text-sm font-medium" style={{ color: textColor }}>{option}</span>
                    {answerFeedback && isCorrect && <CheckCircle size={15} style={{ color: '#22c55e', flexShrink: 0 }} />}
                    {answerFeedback && isWrong   && <span className="font-bold shrink-0" style={{ color: '#ef4444' }}>✗</span>}
                    {answerSubmitting && isSelected && (
                      <div className="w-4 h-4 border-2 border-t-transparent rounded-full animate-spin shrink-0" style={{ borderColor: '#1e3a8a' }} />
                    )}
                  </label>
                );
              })}
            </div>

            {/* Inline feedback for < lg, where the right-hand rail is hidden.
                Without this, every tablet and phone user answered a question and
                got no explanation at all. */}
            {feedbackBody && (
              <div
                className="lg:hidden rounded-xl overflow-hidden mb-6"
                style={{ background: '#fafafa', border: '1px solid #f3f4f6' }}
              >
                {feedbackBody}
              </div>
            )}

            {/* One control bar, one alignment axis. Previously a centre-aligned
                row sat above a space-between row, and BOTH "Submit" and "Skip"
                called handleNext while "Show Answer" actually flagged for review —
                three labels for two actions. Labels now match behaviour. */}
            <div className="flex items-center justify-between gap-3 flex-wrap mt-auto pt-6 border-t" style={{ borderColor: '#f3f4f6' }}>
              <div className="flex items-center gap-2">
                {currentQuestion?.selected && !currentQuestion?.locked && (
                  <button
                    onClick={handleClearAnswer}
                    className="px-3 py-2 rounded-md border text-[11px] font-bold tracking-wider uppercase transition hover:bg-slate-50"
                    style={{ borderColor: '#e5e7eb', color: '#6b7280' }}
                  >
                    Clear
                  </button>
                )}
                <button
                  onClick={() => setShowReportModal(true)}
                  className="px-3 py-2 rounded-md border text-[11px] font-bold tracking-wider uppercase transition hover:bg-orange-50"
                  style={{ borderColor: '#fed7aa', color: '#ea580c' }}
                >
                  ⚠ Report
                </button>
              </div>
              <div className="flex items-center gap-2">
                <button
                  onClick={handleMarkForReview}
                  title="Keyboard shortcut: press F"
                  aria-keyshortcuts="f"
                  aria-pressed={!!currentQuestion?.markedForReview}
                  className="px-3 py-2 rounded-md border text-[11px] font-bold tracking-wider uppercase transition hover:bg-blue-50"
                  style={{
                    borderColor: currentQuestion?.markedForReview ? '#fde68a' : '#e5e7eb',
                    color:       currentQuestion?.markedForReview ? '#92400e' : '#6b7280',
                    background:  currentQuestion?.markedForReview ? '#fef3c7' : 'transparent',
                  }}
                >
                  {currentQuestion?.markedForReview ? '★ Marked' : 'Mark for review'}
                </button>
                <button
                  onClick={handlePrevious}
                  disabled={currentQ === 0}
                  className="flex items-center gap-1 px-3 py-2 rounded-md text-[11px] font-bold tracking-wider uppercase transition disabled:opacity-40 hover:bg-slate-50"
                  style={{ border: '1px solid #e5e7eb', color: '#6b7280' }}
                >
                  <ChevronLeft size={12} /> Prev
                </button>
                {/* Last question: the Next slot becomes the Submit action, so the
                    candidate submits from where they are already looking rather
                    than hunting for a control. The header Submit is hidden while
                    this is showing, so there is still only ever ONE submit button
                    on screen. */}
                {isOnLastQuestion ? (
                  <button
                    onClick={handleSectionSubmit}
                    disabled={sectionSubmitting}
                    title="Keyboard shortcut: press S"
                    aria-keyshortcuts="s"
                    className="flex items-center gap-1.5 px-4 py-2 rounded-md text-[11px] font-bold tracking-wider uppercase text-white transition disabled:opacity-60 hover:opacity-90"
                    style={{
                      background: isLastSection ? '#059669' : '#1e3a8a',
                      boxShadow: `0 0 0 3px ${isLastSection ? '#a7f3d0' : '#bfdbfe'}`,
                    }}
                  >
                    <CheckCircle size={12} />
                    {sectionSubmitting ? 'Submitting…' : isLastSection ? 'Submit Test' : 'Submit Section'}
                  </button>
                ) : (
                  <button
                    onClick={handleNext}
                    className="flex items-center gap-1 px-4 py-2 rounded-md text-[11px] font-bold tracking-wider uppercase text-white transition hover:opacity-90"
                    style={{ background: '#1e3a8a' }}
                  >
                    Next <ChevronRight size={12} />
                  </button>
                )}
              </div>
            </div>
          </div>
        </motion.div>

        {/* Right: feedback panel — light, purple accents — hidden until lg */}
        <div
          className="hidden lg:flex w-72 shrink-0 flex-col overflow-y-auto border-l"
          style={{ background: '#fafafa', borderColor: '#f3f4f6' }}
        >
          <AnimatePresence mode="wait">
            {feedbackBody ? (
              <motion.div key="feedback" initial={{ opacity: 0 }} animate={{ opacity: 1 }} className="flex-1 flex flex-col">
                {feedbackBody}
              </motion.div>
            ) : (
              <motion.div key="placeholder" initial={{ opacity: 0 }} animate={{ opacity: 1 }} className="p-4">
                <p className="text-[10px] font-bold tracking-widest mb-1" style={{ color: '#9ca3af' }}>ANSWER</p>
                <p className="text-xs" style={{ color: '#9ca3af' }}>Select an option to see feedback</p>
              </motion.div>
            )}
          </AnimatePresence>

          {/* Section stats */}
          <div className="p-4 border-t shrink-0" style={{ borderColor: '#f3f4f6' }}>
            <p className="text-[10px] font-bold tracking-widest mb-3" style={{ color: '#9ca3af' }}>THIS SECTION</p>
            <div className="grid grid-cols-3 gap-2">
              <div className="text-center p-2.5 rounded-xl" style={{ background: '#f0fdf4', border: '1px solid #bbf7d0' }}>
                <div className="text-lg font-bold" style={{ color: '#15803d' }}>{answered}</div>
                <div className="text-[10px] font-bold tracking-wider uppercase" style={{ color: '#22c55e' }}>Done</div>
              </div>
              <div className="text-center p-2.5 rounded-xl" style={{ background: '#eff6ff', border: '1px solid #bfdbfe' }}>
                <div className="text-lg font-bold" style={{ color: '#1e3a8a' }}>{notAnswered}</div>
                <div className="text-[10px] font-bold tracking-wider uppercase" style={{ color: '#60a5fa' }}>Left</div>
              </div>
              <div className="text-center p-2.5 rounded-xl" style={{ background: '#fffbeb', border: '1px solid #fde68a' }}>
                <div className="text-lg font-bold" style={{ color: '#b45309' }}>{flagged}</div>
                <div className="text-[10px] font-bold tracking-wider uppercase" style={{ color: '#f59e0b' }}>Flag</div>
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* Bottom status bar. Wraps instead of overflowing: this was a single
          non-wrapping row of eight items and pushed a horizontal scrollbar onto
          the whole page below ~640px. */}
      <div
        className="flex items-center justify-between gap-x-4 gap-y-1.5 flex-wrap px-4 md:px-6 py-2.5 border-t shrink-0 text-[11px]"
        style={{ background: '#ffffff', borderColor: '#f3f4f6' }}
      >
        <div className="flex items-center gap-x-3 gap-y-1 flex-wrap" style={{ color: '#9ca3af' }}>
          <span className="hidden sm:flex items-center gap-1.5">
            <CheckCircle size={10} style={{ color: '#22c55e' }} aria-hidden="true" />
            <span className="font-semibold tracking-wider uppercase">Network OK</span>
          </span>
          <span className="hidden sm:inline" style={{ color: '#d1d5db' }}>·</span>
          <span className="font-semibold tracking-wider uppercase">Autosave</span>
          <span style={{ color: '#d1d5db' }}>·</span>
          <span className="font-semibold tracking-wider uppercase">
            {String(currentQ + 1).padStart(2, '0')}/{String(questions.length).padStart(2, '0')}
          </span>
          <span style={{ color: '#d1d5db' }}>·</span>
          <span className="font-semibold tracking-wider uppercase" style={{ color: '#15803d' }}>{answered} Answered</span>
          <span style={{ color: '#d1d5db' }}>·</span>
          <span className="font-semibold tracking-wider uppercase">{notAnswered} Remaining</span>
          {flagged > 0 && (
            <>
              <span style={{ color: '#d1d5db' }}>·</span>
              <span className="font-semibold tracking-wider uppercase" style={{ color: '#b45309' }}>{flagged} Marked</span>
            </>
          )}
        </div>
        <div className="hidden md:block text-[10px] font-medium" style={{ color: '#60a5fa' }}>
          You can skip this question anytime — your selection is auto-saved.
        </div>
      </div>

      {/* Report issue modal */}
      {showReportModal && (
        <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50 p-4">
          <motion.div
            initial={{ opacity: 0, scale: 0.95 }}
            animate={{ opacity: 1, scale: 1 }}
            className="bg-white rounded-xl p-6 max-w-md w-full shadow-2xl"
            role="dialog"
            aria-modal="true"
            aria-labelledby="report-issue-title"
          >
            <h2 id="report-issue-title" className="text-base font-bold mb-1" style={{ color: '#000' }}>Report an Issue</h2>
            <p className="text-xs mb-4" style={{ color: '#2d2d2d', opacity: 0.6 }}>Question {currentQ + 1} — describe the problem</p>
            <textarea
              value={reportReason}
              onChange={e => setReportReason(e.target.value)}
              placeholder="e.g. Wrong answer key, typo, missing option..."
              rows={4}
              className="w-full border rounded-lg px-3 py-2 text-sm outline-none resize-none mb-4"
              style={{ borderColor: '#e5e7eb' }}
            />
            <div className="flex gap-3">
              <button
                onClick={() => { setShowReportModal(false); setReportReason(''); }}
                className="flex-1 py-2 border rounded-lg text-sm font-semibold transition"
                style={{ borderColor: '#e5e7eb', color: '#2d2d2d' }}
              >
                Cancel
              </button>
              <button
                onClick={handleReportIssue}
                disabled={!reportReason.trim() || reportSubmitting}
                className="flex-1 py-2 rounded-lg text-sm font-bold text-white transition disabled:opacity-50"
                style={{ background: '#ef4444' }}
              >
                {reportSubmitting ? 'Submitting...' : 'Submit Report'}
              </button>
            </div>
          </motion.div>
        </div>
      )}
    </div>
  );
}
