// Employment Information Options
export const industries = [
    "IT",
    "Finance",
    "Healthcare",
    "Education",
    "E-commerce",
    "Manufacturing",
    "Retail",
    "Telecommunications",
    "Media & Entertainment",
    "Consulting",
    "Insurance",
    "Real Estate",
    "Automotive",
    "Energy & Utilities",
    "Logistics & Transportation",
    "Agriculture",
    "Construction",
    "Hospitality & Tourism",
    "Pharmaceutical",
    "Banking",
];

export const roles = [
    "Software Developer",
    "Software Engineer",
    "Frontend Developer",
    "React Developer",
    "Next.js Developer",
    "Angular Developer",
    "Vue.js Developer",
    "Backend Developer",
    "Java Developer",
    "Python Developer",
    "Node.js Developer",
    "Ruby Developer",
    "Fullstack Developer",
    "UI/UX Designer",
    "DevOps Engineer",
    "QA Engineer",
    "Quality Assurance",
    "Data Scientist",
    "Data Analyst",
    "Data Engineer",
    "Machine Learning Engineer",
    "Product Manager",
    "Project Manager",
    "Business Analyst",
    "Business Development",
    "Solutions Architect",
    "Systems Administrator",
    "Cloud Engineer",
    "Mobile Developer",
    "iOS Developer",
    "Android Developer",
    "Game Developer",
    "Embedded Systems Engineer",
    "Security Engineer",
    "Network Administrator",
    "Database Administrator",
    "Technical Lead",
    "Engineering Manager",
    "Scrum Master",
    "Test Automation Lead",
];

export const locations = [
    "Hyderabad",
    "Bangalore",
    "Chennai",
    "Pune",
    "Delhi",
    "Mumbai",
    "Gurugram",
    "Gurgaon",
    "Noida",
    "Greater Noida",
    "Kolkata",
    "Jaipur",
    "Ludhiana",
    "Chandigarh",
    "Ahmedabad",
    "Indore",
    "Surat",
    "Vadodara",
    "Kochi",
    "Coimbatore",
    "Visakhapatnam",
    "Lucknow",
    "Nagpur",
    "Pune Metropolitan Area",
];

export const jobTypes = [
    { label: "Full-time", value: "full_time" },
    { label: "Part-time", value: "part_time" },
    { label: "Contract", value: "contract" },
    { label: "Internship", value: "internship" },
    { label: "Freelance", value: "freelance" },
];

export const noticePeriod = [
    { label: "0", value: "0" },
    { label: "7", value: "7" },
    { label: "15", value: "15" },
    { label: "30", value: "30" },
    { label: "45", value: "45" },
    { label: "60", value: "60" },
];
