// Comprehensive list of technical and professional skills
export const suggestedSkills = [
    // Frontend Technologies
    "React",
    "Next.js",
    "Vue.js",
    "Angular",
    "TypeScript",
    "JavaScript",
    "HTML5",
    "CSS3",
    "Tailwind CSS",
    "Bootstrap",
    "Material UI",
    "Redux",
    "State Management",
    "REST API",
    "GraphQL",

    // Backend Technologies
    "Node.js",
    "Express.js",
    "Python",
    "Django",
    "Flask",
    "Java",
    "Spring Boot",
    "C#",
    ".NET",
    "Ruby",
    "Ruby on Rails",
    "PHP",
    "Laravel",
    "Go",
    "Rust",

    // Database & Data
    "SQL",
    "PostgreSQL",
    "MySQL",
    "MongoDB",
    "Firebase",
    "Redis",
    "Elasticsearch",
    "Data Structures",
    "Database Design",

    // Cloud & DevOps
    "AWS",
    "Google Cloud",
    "Azure",
    "Docker",
    "Kubernetes",
    "CI/CD",
    "Jenkins",
    "GitHub Actions",
    "Linux",
    "System Administration",
    "AWS Lambda",
    "Serverless",

    // Mobile Development
    "React Native",
    "Flutter",
    "Swift",
    "Kotlin",
    "Android",
    "iOS",
    "Mobile Development",

    // Data Science & AI
    "Machine Learning",
    "Deep Learning",
    "TensorFlow",
    "PyTorch",
    "Scikit-learn",
    "Pandas",
    "NumPy",
    "Data Analysis",
    "Tableau",
    "Power BI",
    "Excel",

    // QA & Testing
    "Jest",
    "Mocha",
    "Chai",
    "Cypress",
    "Selenium",
    "JUnit",
    "TestNG",
    "Postman",
    "API Testing",
    "Unit Testing",
    "Integration Testing",
    "Automation Testing",

    // Version Control & Tools
    "Git",
    "GitHub",
    "GitLab",
    "Bitbucket",
    "SVN",
    "Jira",
    "Confluence",
    "Slack",

    // Development Practices
    "Agile",
    "Scrum",
    "Kanban",
    "Test Driven Development",
    "Microservices",
    "Design Patterns",
    "Clean Code",
    "Code Review",
    "Refactoring",
    "Problem Solving",
    "Algorithm Design",

    // Soft Skills
    "Communication",
    "Team Leadership",
    "Project Management",
    "Mentoring",
    "Problem Solving",
    "Critical Thinking",
    "Time Management",
    "Collaboration",
    "Adaptability",
    "Attention to Detail",

    // DevOps & Infrastructure
    "Infrastructure as Code",
    "Terraform",
    "Ansible",
    "Prometheus",
    "Grafana",
    "Monitoring",
    "Logging",
    "Load Balancing",
    "Nginx",
    "Apache",

    // Web Technologies
    "Webpack",
    "Vite",
    "NPM",
    "Yarn",
    "SASS",
    "LESS",
    "Web Performance",
    "SEO",
    "Accessibility",
    "Progressive Web Apps",

    // Other Technologies
    "Git Workflow",
    "OAuth",
    "JWT",
    "API Design",
    "Microservices Architecture",
    "System Design",
    "Security",
    "Web Security",
    "Encryption",
    "Authentication",
];
