export const languages = [
    // Indian Languages
    "Hindi",
    "Bengali",
    "Telugu",
    "Marathi",
    "Tamil",
    "Urdu",
    "Gujarati",
    "Kannada",
    "Odia",
    "Malayalam",
    "Punjabi",
    "Assamese",
    "Maithili",
    "Santali",
    "Kashmiri",
    "Nepali",
    "Konkani",
    "Sindhi",
    "Manipuri (Meitei)",
    "Dogri",
    "Bodo",
    "Sanskrit",
    "Rajasthani",
    "Bhili/Bhilodi",
    "Gondi",
    "Ho",
    "Mundari",
    "Kurukh",
    "Khasi",
    "Mizo",
    "Tripuri",
    "Tulu",

    // Foreign Languages
    "English",
    "French",
    "German",
    "Spanish",
    "Portuguese",
    "Italian",
    "Russian",
    "Chinese (Mandarin)",
    "Japanese",
    "Korean",
    "Arabic",
];
