// Shared auth-screen styles (TS port of POC src/styles/authStyles.js).

import { StyleSheet } from 'react-native';

export const authStyles = StyleSheet.create({
  panel: { width: '100%' },
  title: {
    color: '#152033',
    fontSize: 26,
    fontWeight: '800',
    marginBottom: 6,
    textAlign: 'center',
  },
  subtitle: {
    color: '#637083',
    fontSize: 14,
    lineHeight: 20,
    marginBottom: 22,
    textAlign: 'center',
  },
  form: { gap: 16 },
  socialSection: { gap: 18, marginBottom: 18 },
  socialButtonGrid: { flexDirection: 'row', gap: 12 },
  socialButton: {
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderColor: '#dce3ec',
    borderRadius: 10,
    borderWidth: 1,
    flex: 1,
    flexDirection: 'row',
    gap: 8,
    justifyContent: 'center',
    minHeight: 48,
    paddingHorizontal: 12,
  },
  socialButtonText: { color: '#25334a', fontSize: 15, fontWeight: '700' },
  authDivider: { alignItems: 'center', flexDirection: 'row', gap: 10 },
  authDividerLine: { backgroundColor: '#dce3ec', flex: 1, height: 1 },
  authDividerText: { color: '#8d98a7', fontSize: 13, fontWeight: '600' },
  formErrorText: {
    backgroundColor: '#fff1f0',
    borderColor: '#ffccc7',
    borderRadius: 8,
    borderWidth: 1,
    color: '#b42318',
    fontSize: 14,
    fontWeight: '700',
    lineHeight: 20,
    marginBottom: 16,
    padding: 12,
  },
  successText: {
    backgroundColor: '#ecfdf3',
    borderColor: '#abefc6',
    borderRadius: 8,
    borderWidth: 1,
    color: '#067647',
    fontSize: 14,
    fontWeight: '700',
    lineHeight: 20,
    marginBottom: 16,
    padding: 12,
  },
  inputGroup: { gap: 7 },
  inputLabel: { color: '#1f2a3d', fontSize: 14, fontWeight: '700' },
  inputWrapper: {
    alignItems: 'center',
    backgroundColor: '#f1f3f6',
    borderColor: '#e4e8ee',
    borderRadius: 10,
    borderWidth: 1,
    flexDirection: 'row',
    minHeight: 52,
    paddingHorizontal: 14,
  },
  input: { color: '#152033', flex: 1, fontSize: 15, minHeight: 52, paddingRight: 10 },
  inputError: { borderColor: '#d92d20' },
  inputIcon: { marginLeft: 4 },
  passwordToggle: { alignItems: 'center', height: 40, justifyContent: 'center', width: 36 },
  errorText: { color: '#d92d20', fontSize: 13, fontWeight: '700' },
  primaryButton: {
    alignItems: 'center',
    backgroundColor: '#2557A7',
    borderRadius: 10,
    justifyContent: 'center',
    marginTop: 22,
    minHeight: 52,
  },
  buttonPressed: { opacity: 0.85 },
  buttonDisabled: { opacity: 0.6 },
  primaryButtonText: { color: '#ffffff', fontSize: 16, fontWeight: '800' },
  signInMetaRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
    justifyContent: 'space-between',
    marginTop: 10,
  },
  inlineErrorText: { color: '#d92d20', flex: 1, fontSize: 13, fontWeight: '700' },
  footerRow: {
    alignItems: 'center',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 5,
    justifyContent: 'center',
    marginTop: 20,
  },
  footerText: { color: '#637083', fontSize: 14 },
  linkText: { color: '#1d4ed8', fontSize: 14, fontWeight: '800' },
  screen: {
    backgroundColor: '#ffffff',
    flex: 1,
    paddingHorizontal: 24,
    paddingTop: 28,
  },
});
