"use client";

import { useState, useCallback, useEffect, useRef, Suspense } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import {
  ChevronRight, ChevronLeft, Code2, Mic, Clock,
  CheckCircle2, Loader2, AlertCircle, Key, RotateCcw,
} from "lucide-react";
import AudioRecorder from "@/app/(interview)/communication/components/AudioRecorder";
import FeedbackCard from "@/app/(interview)/mock-interview/_components/FeedbackCard";
import TranscriptDisplay from "@/app/(interview)/mock-interview/_components/TranscriptDisplay";
import {
  startPractice, submitPracticeAnswer, generateTechnicalQuestions, MrTrQuestion, SubmitAnswerResponse,
} from "@/api/mockInterviewApi";

const TECH_QUESTIONS_KEY = "tech_generated_questions";
import { useMockInterview } from "@/app/(interview)/mock-interview/_context/MockInterviewContext";

// ─── Types ────────────────────────────────────────────────────────────────────

type AnswerState = {
  transcript: string;
  duration: number;
  fillerCount: number;
  keyPointsHit: string[];
  dimensions: { label: string; score: number; weight: string }[];
  weightedScore: number;
  feedback: string;
  improvedAnswer: string;
  answerId?: string;
  whatWasGood?: string[];
  whatToImprove?: string[];
  fillerWords?: { word: string; count: number }[];
  fillerTip?: string;
  targetDurationMin?: number;
  targetDurationMax?: number;
  lengthNote?: string;
  speechRate?: number;
  pauseAnalysis?: string;
  encouragement?: string;
  attemptNumber?: number;
} | null;

type Question = {
  id: string;
  text: string;
  keywords: string[];
  expected_duration_s: number;
};

// ─── Content ──────────────────────────────────────────────────────────────────

function TechnicalPracticeContent() {
  const router = useRouter();
  const searchParams = useSearchParams();
  const { setPracticeAnswered } = useMockInterview();
  const errorDismissRef = useRef<ReturnType<typeof setTimeout> | null>(null);
  const timerRef = useRef<ReturnType<typeof setInterval> | null>(null);

  const category = searchParams.get("category") ?? "dsa";
  const categoryMap: Record<string, string> = {
    dsa: "technical", web: "technical", backend: "technical",
    database: "technical", core: "technical",
  };
  const backendCategory = categoryMap[category] ?? "technical";

  const [sessionId, setSessionId] = useState<string | null>(null);
  const [questions, setQuestions] = useState<Question[]>([]);
  const [sessionError, setSessionError] = useState<string | null>(null);
  const [sessionLoading, setSessionLoading] = useState(true);
  const [currentIndex, setCurrentIndex] = useState(0);
  const [answeredMap, setAnsweredMap] = useState<Record<string, AnswerState>>({});
  const [currentAnswer, setCurrentAnswer] = useState<AnswerState>(null);
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [submitError, setSubmitError] = useState<string | null>(null);
  const [elapsedSeconds, setElapsedSeconds] = useState(0);

  const showSubmitError = useCallback((msg: string) => {
    if (errorDismissRef.current) clearTimeout(errorDismissRef.current);
    setSubmitError(msg);
    errorDismissRef.current = setTimeout(() => setSubmitError(null), 5000);
  }, []);

  useEffect(() => {
    // Read questions pre-generated by the technical info page
    let pregenQuestions: MrTrQuestion[] | null = null;
    try {
      const raw = sessionStorage.getItem(TECH_QUESTIONS_KEY);
      if (raw) {
        pregenQuestions = JSON.parse(raw) as MrTrQuestion[];
        sessionStorage.removeItem(TECH_QUESTIONS_KEY);
      }
    } catch {}

    if (pregenQuestions && pregenQuestions.length > 0) {
      // Use pre-generated questions; get session_id separately for answer submission
      startPractice({ round_number: 1, category: backendCategory })
        .then((data) => setSessionId(data.session_id))
        // Do NOT swallow this. Without a session_id, handleRecordingComplete
        // returns immediately, so the recorder renders enabled and the
        // candidate's answers are silently discarded. Surface the retry state.
        .catch(() =>
          setSessionError("Could not start the practice session. Please try again."),
        );
      setQuestions(
        (pregenQuestions as MrTrQuestion[]).map((q) => ({
          id: q.question_id,
          text: q.question_text,
          keywords: q.key_points ?? [],
          expected_duration_s: q.time_limit_seconds,
        }))
      );
      setSessionLoading(false);
    } else {
      // Fallback: generate via the old endpoint
      Promise.allSettled([
        startPractice({ round_number: 1, category: backendCategory }),
        generateTechnicalQuestions({
          skills: [category],
          num_questions: 10,
          experience_level: localStorage.getItem("mock_experience_level") === "experienced" ? "mid" : "fresher",
        }),
      ]).then(([sessionResult, questionsResult]) => {
        if (sessionResult.status === "fulfilled") {
          setSessionId(sessionResult.value.session_id);
        }
        if (questionsResult.status === "fulfilled" && questionsResult.value.questions.length > 0) {
          setQuestions(
            questionsResult.value.questions.map((q) => ({
              id: q.question_id,
              text: q.question_text,
              keywords: q.key_points ?? [],
              expected_duration_s: 90,
            }))
          );
        } else {
          setSessionError("Could not load questions for this category. Please try again.");
        }
      }).finally(() => setSessionLoading(false));
    }
  }, [category, backendCategory]);

  useEffect(() => {
    if (!currentAnswer && !isSubmitting) {
      setElapsedSeconds(0);
      timerRef.current = setInterval(() => setElapsedSeconds((s) => s + 1), 1000);
    } else {
      if (timerRef.current) clearInterval(timerRef.current);
    }
    return () => { if (timerRef.current) clearInterval(timerRef.current); };
  }, [currentAnswer, isSubmitting]);

  const question = questions[currentIndex];
  const isLastQuestion = currentIndex === questions.length - 1;
  const answeredCount = Object.keys(answeredMap).length;

  const handleRecordingComplete = useCallback(async (blob: Blob, durationMs?: number) => {
    if (!sessionId || !question) return;

    if (durationMs !== undefined && durationMs < 2000) {
      showSubmitError("No speech detected. Please speak clearly for at least 2 seconds when recording.");
      return;
    }

    setIsSubmitting(true);
    setCurrentAnswer(null);

    try {
      const formData = new FormData();
      formData.append("audio", blob, "answer.webm");
      formData.append("session_id", sessionId);
      formData.append("question_id", question.id);

      const api = await submitPracticeAnswer(formData);
      const answer: AnswerState = {
        transcript: api.transcript,
        duration: durationMs !== undefined ? Math.round(durationMs / 1000) : 0,
        fillerCount: api.rule_scores.filler_count,
        keyPointsHit: api.rule_scores.key_points_hit,
        weightedScore: api.scores.weighted_score,
        feedback: api.feedback.improvements.join(" "),
        improvedAnswer: api.feedback.improved_answer,
        whatWasGood: api.feedback.good_points,
        whatToImprove: api.feedback.improvements,
        encouragement: api.feedback.encouragement,
        dimensions: [
          { label: "Content",   score: api.scores.content_score,   weight: "40%" },
          { label: "Clarity",   score: api.scores.clarity_score,   weight: "30%" },
          { label: "Structure", score: api.scores.structure_score, weight: "20%" },
          { label: "Length",    score: api.scores.length_score,    weight: "10%" },
        ],
        targetDurationMin: Math.round(question.expected_duration_s * 0.7),
        targetDurationMax: question.expected_duration_s,
      };
      setAnsweredMap((m) => ({ ...m, [question.id]: answer }));
      setCurrentAnswer(answer);
    } catch {
      showSubmitError("Could not score your answer. Please check your connection and try again.");
    } finally {
      setIsSubmitting(false);
    }
  }, [sessionId, question, showSubmitError]);

  const handleNext = () => {
    setCurrentAnswer(null);
    setPracticeAnswered(Object.keys(answeredMap).length);
    if (isLastQuestion) {
      router.push("/mock-interview/live");
    } else {
      setCurrentIndex((i) => i + 1);
    }
  };

  const handleTryAgain = () => setCurrentAnswer(null);

  const warningThreshold = (question?.expected_duration_s ?? 90) * 1.5;
  const showLongAnswerWarning = elapsedSeconds > warningThreshold && !currentAnswer && !isSubmitting;

  // ── Loading ──
  if (sessionLoading) {
    return (
      <div className="flex items-center justify-center min-h-[60vh]">
        <div className="text-center">
          <Loader2 size={28} className="text-[#2557a7] animate-spin mx-auto mb-3" />
          <p className="text-sm text-gray-500">Preparing questions…</p>
        </div>
      </div>
    );
  }

  // ── Error ──
  if (sessionError || questions.length === 0) {
    return (
      <div className="flex items-center justify-center min-h-[60vh] px-4">
        <div className="text-center max-w-sm">
          <div className="w-14 h-14 bg-gray-100 rounded-full flex items-center justify-center mx-auto mb-4">
            <AlertCircle size={24} className="text-gray-400" />
          </div>
          <h2 className="text-base font-bold text-gray-900 mb-2">Questions Unavailable</h2>
          <p className="text-sm text-gray-500 mb-4">{sessionError ?? "No questions were returned for this category."}</p>
          <div className="flex gap-3 justify-center">
            <button
              onClick={() => router.push("/notes/technical")}
              className="px-4 py-2.5 bg-white border border-gray-200 text-gray-700 rounded-xl text-sm font-semibold hover:bg-gray-50"
            >
              Back
            </button>
            <button
              onClick={() => { setSessionError(null); setSessionLoading(true); }}
              className="px-4 py-2.5 bg-[#2557a7] text-white rounded-xl text-sm font-semibold hover:bg-[#1e4a8f] transition-all"
            >
              Retry
            </button>
          </div>
        </div>
      </div>
    );
  }

  if (!question) {
    return (
      <div className="flex items-center justify-center min-h-[60vh]">
        <div className="text-center">
          <Loader2 size={28} className="text-[#2557a7] animate-spin mx-auto mb-3" />
          <p className="text-sm text-gray-500">Loading questions…</p>
        </div>
      </div>
    );
  }

  // ── Main UI ──
  return (
    <div className="max-w-6xl mx-auto px-4 sm:px-6 py-8">

      <button
        onClick={() => router.push("/notes/technical")}
        className="flex items-center gap-1.5 text-xs text-gray-500 hover:text-gray-700 mb-5 transition-colors"
      >
        <ChevronLeft size={14} /> Back
      </button>

      {/* Submit error */}
      {submitError && (
        <div role="alert" className="mb-4 flex items-start justify-between gap-3 bg-red-50 border border-red-200 rounded-xl px-4 py-3">
          <div className="flex items-start gap-2.5">
            <AlertCircle size={14} className="text-red-500 mt-0.5 shrink-0" />
            <p className="text-xs text-red-700 font-medium">{submitError}</p>
          </div>
          <button onClick={() => setSubmitError(null)} className="text-red-400 hover:text-red-600 text-xs shrink-0">Dismiss</button>
        </div>
      )}

      {/* Long answer warning */}
      {showLongAnswerWarning && (
        <div role="alert" className="mb-4 flex items-start gap-2.5 bg-[#2557a7]/5 border border-[#2557a7]/20 rounded-xl px-4 py-3">
          <Clock size={14} className="text-[#2557a7] mt-0.5 shrink-0" />
          <p className="text-xs text-gray-700 font-medium">
            Your answer is getting long. Try to wrap up — aim for {question.expected_duration_s}s.
          </p>
        </div>
      )}

      {/* Header: title + question circles */}
      <div className="flex items-center justify-between mb-6 flex-wrap gap-3">
        <div>
          <div className="flex items-center gap-2 mb-1">
            <span className="text-xs font-bold px-2.5 py-1 bg-[#2557a7]/10 text-[#2557a7] rounded-full capitalize">
              {category.toUpperCase() === "DSA" ? "DSA" : category}
            </span>
          </div>
          <h1 className="text-xl font-bold text-gray-900">Technical Practice</h1>
        </div>

        <div className="flex items-center gap-2 flex-wrap">
          {questions.map((q, i) => (
            <button
              key={q.id}
              onClick={() => { setCurrentIndex(i); setCurrentAnswer(answeredMap[q.id] ?? null); }}
              className={`w-8 h-8 rounded-full text-xs font-bold transition-all ${
                i === currentIndex
                  ? "bg-[#2557a7] text-white shadow-md scale-110"
                  : answeredMap[q.id]
                  ? "bg-[#2557a7]/10 text-[#2557a7] border border-[#2557a7]/30"
                  : "bg-gray-100 text-gray-500 border border-gray-200 hover:bg-gray-200"
              }`}
            >
              {answeredMap[q.id] ? <CheckCircle2 size={14} className="mx-auto" /> : i + 1}
            </button>
          ))}
        </div>
      </div>

      {/* Progress bar */}
      <div className="mb-6">
        <div className="flex justify-between text-xs text-gray-500 mb-1">
          <span>Question {currentIndex + 1} of {questions.length}</span>
          <span>{answeredCount} answered</span>
        </div>
        <div className="h-1.5 bg-gray-200 rounded-full overflow-hidden">
          <div
            role="progressbar"
            aria-valuenow={currentIndex}
            aria-valuemin={0}
            aria-valuemax={questions.length}
            className="h-full bg-[#2557a7] rounded-full transition-all duration-500"
            style={{ width: `${(currentIndex / questions.length) * 100}%` }}
          />
        </div>
      </div>

      {/* Two-column layout */}
      <div className="grid grid-cols-1 lg:grid-cols-[1fr_380px] gap-6">

        {/* Left column */}
        <div className="space-y-4">

          {/* Question card */}
          <div className="bg-white border border-gray-200 rounded-xl shadow-[0_1px_3px_rgba(0,0,0,0.04),0_4px_16px_rgba(0,0,0,0.04)] overflow-hidden">
            <div className="h-0.75 bg-linear-to-r from-[#2557a7] to-[#5b8fd6]" />
            <div className="px-5 pt-3.5 pb-3 border-b border-gray-100">
              <div className="flex items-center justify-between">
                <div className="flex items-center gap-2">
                  <span className="text-[10px] font-bold text-gray-400 uppercase tracking-widest">Question {currentIndex + 1}</span>
                  <span className="text-[10px] px-2 py-0.5 rounded-full font-semibold bg-gray-100 text-gray-500">technical</span>
                </div>
                <div className="flex items-center gap-1.5 text-gray-400 text-xs font-medium">
                  <Clock size={12} />
                  {question.expected_duration_s}s target
                </div>
              </div>
            </div>
            <div className="px-5 py-5">
              <p className="text-lg font-bold text-gray-900 leading-snug">{question.text}</p>
            </div>
          </div>

          {/* Keywords panel */}
          {question.keywords.length > 0 && (
            <div className="rounded-xl border border-gray-200 bg-gray-50 px-4 py-3">
              <div className="flex items-center gap-2 mb-2.5">
                <Key size={13} className="text-gray-500" />
                <span className="text-xs font-semibold text-gray-600">Key points to cover</span>
              </div>
              <div className="flex flex-wrap gap-2">
                {question.keywords.map((kw, i) => (
                  <span key={i} className="text-xs font-semibold bg-[#2557a7]/10 text-[#2557a7] border border-[#2557a7]/20 rounded-lg px-2.5 py-1">
                    {kw}
                  </span>
                ))}
              </div>
            </div>
          )}

          {/* Recorder */}
          {!currentAnswer && !isSubmitting && (
            <div className="bg-white border border-gray-200 rounded-xl shadow-[0_1px_3px_rgba(0,0,0,0.04),0_4px_16px_rgba(0,0,0,0.04)] p-6">
              <div className="flex items-center gap-2 mb-4">
                <Mic size={16} className="text-[#2557a7]" />
                <p className="text-sm font-semibold text-gray-700">Record Your Answer</p>
              </div>
              <AudioRecorder
                onRecordingComplete={handleRecordingComplete}
                maxDuration={Math.min(Math.round(question.expected_duration_s * 1.5), 120)}
              />
            </div>
          )}

          {/* Submitting */}
          {isSubmitting && (
            <div className="bg-white border border-gray-200 rounded-xl shadow-[0_1px_3px_rgba(0,0,0,0.04),0_4px_16px_rgba(0,0,0,0.04)] p-10 flex flex-col items-center gap-3">
              <Loader2 size={32} className="text-[#2557a7] animate-spin" />
              <p className="text-sm font-semibold text-gray-600">Analysing your answer…</p>
              <p className="text-xs text-gray-400">Transcribing → Checking → Scoring</p>
            </div>
          )}

          {/* Transcript */}
          {currentAnswer && (
            <TranscriptDisplay
              transcript={currentAnswer.transcript}
              duration={currentAnswer.duration}
              fillerCount={currentAnswer.fillerCount}
              keyPointsHit={currentAnswer.keyPointsHit}
            />
          )}

          {/* Navigation buttons */}
          {currentAnswer && (
            <div className="flex gap-3">
              {currentIndex > 0 && (
                <button
                  onClick={() => { setCurrentIndex((i) => i - 1); setCurrentAnswer(answeredMap[questions[currentIndex - 1].id] ?? null); }}
                  className="flex items-center gap-1.5 px-4 py-2.5 bg-white border border-gray-200 text-gray-600 rounded-xl text-sm font-semibold hover:bg-gray-50 shadow-sm"
                >
                  <ChevronLeft size={15} /> Back
                </button>
              )}
              <button
                onClick={handleTryAgain}
                className="flex items-center gap-1.5 px-4 py-2.5 bg-white border border-gray-200 text-gray-700 rounded-xl text-sm font-semibold hover:bg-gray-50 shadow-sm transition-all"
              >
                <RotateCcw size={14} className="text-gray-500" /> Record Again
              </button>
              <button
                onClick={handleNext}
                className="flex-1 flex items-center justify-center gap-2 py-2.5 bg-[#2557a7] text-white rounded-xl text-sm font-bold hover:bg-[#1e4a8f] transition-all shadow-md"
              >
                {isLastQuestion ? "Start Live Interview" : "Next Question"}
                <ChevronRight size={15} />
              </button>
            </div>
          )}
        </div>

        {/* Right column — FeedbackCard */}
        <div>
          {currentAnswer ? (
            <FeedbackCard
              weightedScore={currentAnswer.weightedScore}
              feedback={currentAnswer.feedback}
              improvedAnswer={currentAnswer.improvedAnswer}
              dimensions={currentAnswer.dimensions}
              whatWasGood={currentAnswer.whatWasGood}
              whatToImprove={currentAnswer.whatToImprove}
              fillerWords={currentAnswer.fillerWords}
              fillerTip={currentAnswer.fillerTip}
              answerDuration={currentAnswer.duration}
              targetDurationMin={currentAnswer.targetDurationMin}
              targetDurationMax={currentAnswer.targetDurationMax}
              lengthNote={currentAnswer.lengthNote}
              speechRate={currentAnswer.speechRate}
              pauseAnalysis={currentAnswer.pauseAnalysis}
              encouragement={currentAnswer.encouragement}
              attemptNumber={currentAnswer.attemptNumber}
              onTryAgain={handleTryAgain}
              answerId={currentAnswer.answerId}
            />
          ) : (
            <div className="bg-white border border-gray-200 rounded-xl shadow-[0_1px_3px_rgba(0,0,0,0.04),0_4px_16px_rgba(0,0,0,0.04)] p-6 flex flex-col items-center justify-center text-center gap-3 min-h-70">
              <div className="w-14 h-14 bg-[#2557a7]/5 rounded-xl flex items-center justify-center">
                <Code2 size={24} className="text-[#2557a7]" />
              </div>
              <p className="text-sm font-semibold text-gray-700">AI Feedback</p>
              <p className="text-xs text-gray-400">
                Record your answer to receive instant AI feedback, score breakdown, and a model answer.
              </p>
            </div>
          )}
        </div>

      </div>
    </div>
  );
}

export default function TechnicalPracticePage() {
  return (
    <Suspense>
      <TechnicalPracticeContent />
    </Suspense>
  );
}
